### ISSUE TITLE
Ubuntu Focal VM loses network configuration due to failed netplan generate

### ISSUE THREAD

**Issue by jzinkweg** [canonical/cloud-init#4133]
# Bug report
VM's based on Ubuntu 20.04, from before 20.04.4 have netplan.io package < 0.103, so they do not support the "new" to: default introduced in [netplan#216](https://github.com/canonical/netplan/pull/216).
When unattended-upgrades are enabled, cloud-init is automatically updated to release 23.1, which includes #4031.
As a result, the netplan generate step fails during boot, failing the cloud-init service and losing network configuration on a second reboot.

## Steps to reproduce the problem
* Provision a VM based on Ubuntu 20.04.3 or earlier, using cloud-init to configure the network interfaces
* Wait for unattended-upgrades to run, or upgrade cloud-init manually
* Reboot
* Observe cloud-init service has failed
* Reboot again
* Observe network configuration is no longer present

## Environment details
- Cloud-init version: 23.1
- Operating System Distribution: Ubuntu 20.04, from before 20.04.4
- Cloud provider, platform or installer type: Triton Datacenter (SmartOS datasource)

## cloud-init logs

```
2023-05-09 16:13:19,483 - stages.py[INFO]: Applying network configuration from ds bringup=False: {'version': 1, 'config': [{'mtu': 1500, 'type': 'physical', 'name': 'net0', 'mac_address': '90:b8:d0:33:00:e8', 'subnets': [{'type': 'sta
tic', 'address': '192.168.40.252/24', 'gateway': '192.168.40.254'}]}, {'type': 'nameserver', 'address': ['192.168.9.225'], 'search': []}]}
2023-05-09 16:13:19,487 - util.py[DEBUG]: Writing to /run/cloud-init/sem/apply_network_config.once - wb: [644] 24 bytes
2023-05-09 16:13:19,488 - __init__.py[DEBUG]: Selected renderer 'netplan' from priority list: ['netplan', 'eni', 'sysconfig']
2023-05-09 16:13:19,495 - subp.py[DEBUG]: Running command ['netplan', 'info'] with allowed return codes [0] (shell=False, capture=True)
2023-05-09 16:13:19,612 - util.py[DEBUG]: Attempting to load yaml from string of length 210 with allowed root types (<class 'dict'>,)
2023-05-09 16:13:19,618 - util.py[DEBUG]: Writing to /etc/netplan/50-cloud-init.yaml - wb: [644] 729 bytes
2023-05-09 16:13:19,619 - subp.py[DEBUG]: Running command ['netplan', 'generate'] with allowed return codes [0] (shell=False, capture=True)
2023-05-09 16:13:19,727 - util.py[WARNING]: failed stage init-local
2023-05-09 16:13:19,727 - util.py[DEBUG]: failed stage init-local
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 767, in status_wrapper
    ret = functor(name, args)
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 433, in main_init
    init.apply_network_config(bring_up=bring_up_interfaces)
  File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 941, in apply_network_config
    return self.distro.apply_network_config(
  File "/usr/lib/python3/dist-packages/cloudinit/distros/__init__.py", line 278, in apply_network_config
    self._write_network_state(network_state, renderer)
  File "/usr/lib/python3/dist-packages/cloudinit/distros/debian.py", line 142, in _write_network_state
    return super()._write_network_state(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/cloudinit/distros/__init__.py", line 167, in _write_network_state
    renderer.render_network_state(network_state)
  File "/usr/lib/python3/dist-packages/cloudinit/net/netplan.py", line 298, in render_network_state
    self._netplan_generate(run=self._postcmds)
  File "/usr/lib/python3/dist-packages/cloudinit/net/netplan.py", line 305, in _netplan_generate
    subp.subp(self.NETPLAN_GENERATE, capture=True)
  File "/usr/lib/python3/dist-packages/cloudinit/subp.py", line 335, in subp
    raise ProcessExecutionError(
cloudinit.subp.ProcessExecutionError: Unexpected error while running command.
Command: ['netplan', 'generate']
Exit code: 1
Reason: -
Stdout:
Stderr:
        (generate:587): GLib-WARNING **: 18:13:19.715: GError set over the top of a previous GError or uninitialized memory.
        This indicates a bug in someone's code. You must ensure an error is NULL before it's set.
        The overwriting error message was: /etc/netplan/50-cloud-init.yaml:20:13: Error in network definition: unicast route must include both a 'to' and 'via' IP
                    -   to: default
                    ^
        /etc/netplan/50-cloud-init.yaml:20:21: Error in network definition: invalid IP family '-1'
                    -   to: default
                            ^
```

**Comment by jzinkweg** [comment]
https://github.com/canonical/cloud-init/blob/ubuntu/bionic-23.1.x/debian/patches/netplan99-cannot-use-default.patch prevents this from happening on 18.04.
Alternatively, netplan.io could be included in unattended-upgrades.

**Comment by TheRealFalcon** [comment]
Thanks for the bug report @jzinkweg . We'll try to get this fixed ASAP.
