### ISSUE TITLE
v23.2.1 failing on ubuntu 22.04 with local variable 'ds_name' referenced before assignment

### ISSUE THREAD

**Issue by anguswilliams** [canonical/cloud-init#4288]
# Bug report

Cloud-init fails with `UnboundLocalError: local variable 'ds_name' referenced before assignment` after upgrading to `23.2.1-0ubuntu0~22.04.1` on Ubuntu 22.04

## Steps to reproduce the problem

* Configure cloud-init to use a a datasource that is prefixed by `DataSource`

## Environment details
- Cloud-init version: 23.2.1-0ubuntu0~22.04.1
- Operating System Distribution: Ubuntu 22.04
- Cloud provider, platform or installer type: Vmware

I have the following datasources set: `datasource_list: [ "DataSourceVMware", "None" ]`

This is an error that was introduced in the Ubuntu 22.04 package `23.2.1-0ubuntu0~22.04.1`. Reverting to the previous package `23.1.2-0ubuntu0~22.04.1` resolved the error

## cloud-init logs

```
2023-07-24 03:32:47,327 - util.py[DEBUG]: failed stage init-local
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 766, in status_wrapper
    ret = functor(name, args)
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 384, in main_init
    init.fetch(existing=existing)
  File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 436, in fetch
    return self._get_data_source(existing=existing)
  File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 327, in _get_data_source
    (ds, dsname) = sources.find_source(
  File "/usr/lib/python3/dist-packages/cloudinit/sources/__init__.py", line 996, in find_source
    ds_list = list_sources(cfg_list, ds_deps, pkg_list)
  File "/usr/lib/python3/dist-packages/cloudinit/sources/__init__.py", line 1042, in list_sources
    ds_name = importer.match_case_insensitive_module_name(ds)
  File "/usr/lib/python3/dist-packages/cloudinit/importer.py", line 50, in match_case_insensitive_module_name
    if module.lower() == ds_name.lower():
UnboundLocalError: local variable 'ds_name' referenced before assignment
```

**Comment by anguswilliams** [comment]
[This function](https://github.com/canonical/cloud-init/blob/23.2.1/cloudinit/importer.py#L35) was introduced in the latest version, I think the fix would be simply to add the following:

```
    if not mod_name.startswith("DataSource"):
        ds_name = f"DataSource{mod_name}"
   else:
       ds_name = mod_name
```
