### ISSUE TITLE
DataSourceVMwareGuestInfo.py - AttributeError: module 'collections' has no attribute 'Mapping'

### ISSUE THREAD

**Issue by jasonrepos** [canonical/cloud-init#4358]
# Bug report
Provisioning Ubuntu 22.04 cloud image to VMware using Terraform provider.  I get the error which is detailed in the logs below (AttributeError: module 'collections' has no attribute 'Mapping').

The issue appears to be on line 445 of /usr/lib/python3/dist-packages/cloudinit/sources/DataSourceVMwareGuestInfo.py

`
if isinstance(network, collections.Mapping):

instead of 

if isinstance(network, collections.abc.Mapping):
`

If I make the above change and then run a cloud-init init then it works okay and the userdata / metadata is applied as expected.

What I wasn't too sure about is that it seems the file DataSourceVMwareGuestInfo.py is created at the time cloud-init runs, so I'm not entirely sure where this file even comes from as it does not appear in this repo?

-rw-r--r--  1 root root 33485 Jul 26 15:49 DataSourceVMware.py
-rw-r--r--  1 root root 25941 Aug 16 14:24 DataSourceVMwareGuestInfo.py
-rw-r--r--  1 root root  4599 Jul 26 15:49 DataSourceVultr.py

## Steps to reproduce the problem
terraform plan
terraform apply
None of the creation of users, network info is performed.
Look at log file /var/log/cloud-init.log and identify the above error.

## Environment details
- Cloud-init version: 23.2.2-0ubuntu0~22.04.1
- Operating System Distribution: Ubuntu 22.04.3 LTS
- Cloud provider, platform or installer type: hashicorp/vsphere v2.4.1

## cloud-init logs

2023-08-16 14:07:02,883 - __init__.py[DEBUG]: Searching for local data source in: ['DataSourceVMwareGuestInfo']
2023-08-16 14:07:02,883 - handlers.py[DEBUG]: start: init-local/search-VMwareGuestInfo: searching for local data from DataSourceVMwareGuestInfo
2023-08-16 14:07:02,883 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceVMwareGuestInfo.DataSourceVMwareGuestInfo'>
2023-08-16 14:07:02,884 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: boot-new-instance
2023-08-16 14:07:02,884 - DataSourceVMwareGuestInfo.py[DEBUG]: Getting guestinfo value for key metadata
2023-08-16 14:07:02,884 - subp.py[DEBUG]: Running command ['/usr/bin/vmware-rpctool', 'info-get guestinfo.metadata'] with allowed return codes [0] (shell=False, capture=True)
2023-08-16 14:07:02,888 - DataSourceVMwareGuestInfo.py[DEBUG]: Getting guestinfo value for key metadata.encoding
2023-08-16 14:07:02,888 - subp.py[DEBUG]: Running command ['/usr/bin/vmware-rpctool', 'info-get guestinfo.metadata.encoding'] with allowed return codes [0] (shell=False, capture=True)
2023-08-16 14:07:02,891 - DataSourceVMwareGuestInfo.py[DEBUG]: Getting encoded data for key=guestinfo.metadata, enc=base64
2023-08-16 14:07:02,891 - DataSourceVMwareGuestInfo.py[DEBUG]: Decoding base64 format guestinfo.metadata
2023-08-16 14:07:02,894 - DataSourceVMwareGuestInfo.py[DEBUG]: loaded metadata {'local-hostname': 'server-dev-ubuntu22', 'instance-id': 'server-dev-ubuntu22', 'network': {'version': 2, 'ethernets': {'ens192': {'dhcp4': True}}}}
2023-08-16 14:07:02,894 - DataSourceVMwareGuestInfo.py[DEBUG]: network data found
2023-08-16 14:07:02,894 - handlers.py[DEBUG]: finish: init-local/search-VMwareGuestInfo: FAIL: no local data found from DataSourceVMwareGuestInfo
2023-08-16 14:07:02,895 - util.py[WARNING]: Getting data from <class 'cloudinit.sources.DataSourceVMwareGuestInfo.DataSourceVMwareGuestInfo'> failed
2023-08-16 14:07:02,895 - util.py[DEBUG]: Getting data from <class 'cloudinit.sources.DataSourceVMwareGuestInfo.DataSourceVMwareGuestInfo'> failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/sources/__init__.py", line 1012, in find_source
    if s.update_metadata_if_supported(
  File "/usr/lib/python3/dist-packages/cloudinit/sources/__init__.py", line 898, in update_metadata_if_supported
    result = self.get_data()
  File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceVMwareGuestInfo.py", line 131, in get_data
    self.metadata = load_metadata()
  File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceVMwareGuestInfo.py", line 445, in load_metadata
    if isinstance(network, collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'

**Comment by blackboxsw** [comment]
Thanks for filing the issue and making cloud-init better.

This is not a cloud-init issue specifically it is either an image creation issue , the vm template that is being sourced or the image build process in VMware/vSphere or terraform  which has injected a supplemental DataSourceVMwareGuestInfo.py module at /usr/lib/python3/dist-packages/cloudinit/sources. That plugin datasource should likely be removed from you base image or vmtemplate prior to launch or you need to choose a different vmteplate to base you launches on.

`DataSourceVMwareGuestInfo.py` historically was a separate datasource plugin that VMware maintained separate from cloud-init upstream. It is part of https://github.com/vmware-archive/cloud-init-vmware-guestinfo/tree/master which has been deprecated as a project in favor of the upstream `cloudinit/sources/DataSourceVMware.py`. 

The speciific trace you are seeing is due to the unmaintained DataSourceVMwareGuestInfo module not being python 3.6 compatible. In python 3.3 the `collections` module introduced the [collections.abc module](https://docs.python.org/3/library/collections.abc.html) which now delivers the Mapping base class.  Your trace is that the DataSourceVMwareGuestInfo unmaintained module is still trying to use `collections.Mapping` instead of `collections.abc.Mapping`.  What will solve this is finding a VMware/terraform image to launch that doesn't inject or contain DataSourceVMwareGuestInfo.py.

I don't think images you are launching with terraform should contain the dropin DataSourceVMWareGuestInfo.py anymore as they should be deprecated and are not maintained by VMware anymore.  This traceback you see is an indication that the drop-in no longer tracks  Many thanks for the contribution @akutz 8b4a9bc7b81e61943af873bad92e2133f8275b0b.

I'll close this issue as it's not something I think upstream cloudinit can help with. but if you have other context/comments you can provide about the specific terraform config that is breaking and any resolution you come to to avoid this pitfall it would be helpful to comment to others what you discover. Feel free to re-open this issue if there are more questions or discussion to be had here. Thanks again.
