### ISSUE TITLE
Datasource vmware vmtoolsd Permission denied

### ISSUE THREAD

**Issue by playerla** [canonical/cloud-init#4475]
# Bug report

Hi, found a bug like #4436
VMWareDatasource not working with secure RPC using new vmtoolsd binary fallback from #4444 (unexpected behaviour, possibly Debian or Linux related)

## Steps to reproduce the problem

1. Set up a VM and enable secure RPC in vmx :
```
guest_rpc.rpci.auth.cmd.info-set = "TRUE"
guest_rpc.rpci.auth.cmd.info-get = "TRUE"
```
2. Install latest cloud-init 
3. Run cloud-init as root :  Datasource discovered but failed with Permission Denied
```
root@vm:/var/log# cloud-init clean --logs && cloud-init -d init --local
```

Expected behaviour : Got the metadata as it should work as root
```
root@vm:/var/log# python3 -c 'from cloudinit.subp import subp; rpctool, arg = "/usr/bin/vmtoolsd", "info-get guestinfo.metadata.encoding"; (stdout, stderr) = subp([rpctool, "--cmd", arg]); print(f"{stdout}|{stderr}")'
base64
|
```

## Environment details
debian-11.7.0-amd64-netinst.iso install VM on VMWare 6.7

## cloud-init logs

```
root@vm:/var/log# cloud-init clean --logs && cloud-init -d init --local
2023-09-29 14:30:24,312 - handlers.py[DEBUG]: start: init-local: searching for local datasources
2023-09-29 14:30:24,312 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2023-09-29 14:30:24,312 - util.py[DEBUG]: Read 17 bytes from /proc/uptime
2023-09-29 14:30:24,312 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2023-09-29 14:30:24,312 - util.py[DEBUG]: Read 3756 bytes from /etc/cloud/cloud.cfg
2023-09-29 14:30:24,312 - util.py[DEBUG]: Attempting to load yaml from string of length 3756 with allowed root types (<class 'dict'>,)
2023-09-29 14:30:24,321 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2023-09-29 14:30:24,321 - util.py[DEBUG]: Read 328 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2023-09-29 14:30:24,321 - util.py[DEBUG]: Attempting to load yaml from string of length 328 with allowed root types (<class 'dict'>,)
2023-09-29 14:30:24,323 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2023-09-29 14:30:24,323 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2023-09-29 14:30:24,323 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2023-09-29 14:30:24,326 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2023-09-29 14:30:24,326 - util.py[DEBUG]: Read 34 bytes from /run/cloud-init/cloud.cfg
2023-09-29 14:30:24,326 - util.py[DEBUG]: Attempting to load yaml from string of length 34 with allowed root types (<class 'dict'>,)
2023-09-29 14:30:24,326 - subp.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
2023-09-29 14:30:24,342 - util.py[DEBUG]: Reading from /etc/os-release (quiet=False)
2023-09-29 14:30:24,342 - util.py[DEBUG]: Read 267 bytes from /etc/os-release
2023-09-29 14:30:24,343 - util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
2023-09-29 14:30:24,343 - util.py[DEBUG]: Read 144 bytes from /proc/1/environ
2023-09-29 14:30:24,343 - util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
2023-09-29 14:30:24,343 - util.py[DEBUG]: Read 1335 bytes from /proc/self/status
2023-09-29 14:30:24,343 - util.py[DEBUG]: Reading from /proc/cmdline (quiet=False)
2023-09-29 14:30:24,343 - util.py[DEBUG]: Read 77 bytes from /proc/cmdline
2023-09-29 14:30:24,343 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2023-09-29 14:30:24,344 - util.py[DEBUG]: loaded blob returned None, returning default.
2023-09-29 14:30:24,348 - util.py[DEBUG]: Attempting to remove /run/cloud-init/status.json
2023-09-29 14:30:24,348 - util.py[DEBUG]: Attempting to remove /run/cloud-init/result.json
2023-09-29 14:30:24,348 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/data/status.json
2023-09-29 14:30:24,348 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/data/result.json
2023-09-29 14:30:24,349 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpw26zq_yp) - w: [644] 469 bytes/chars
2023-09-29 14:30:24,349 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/status.json' => '../../var/lib/cloud/data/status.json'
2023-09-29 14:30:24,349 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2023-09-29 14:30:24,349 - util.py[DEBUG]: Read 17 bytes from /proc/uptime
2023-09-29 14:30:24,349 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2023-09-29 14:30:24,349 - util.py[DEBUG]: Read 3756 bytes from /etc/cloud/cloud.cfg
2023-09-29 14:30:24,349 - util.py[DEBUG]: Attempting to load yaml from string of length 3756 with allowed root types (<class 'dict'>,)
2023-09-29 14:30:24,358 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2023-09-29 14:30:24,358 - util.py[DEBUG]: Read 328 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2023-09-29 14:30:24,358 - util.py[DEBUG]: Attempting to load yaml from string of length 328 with allowed root types (<class 'dict'>,)
2023-09-29 14:30:24,360 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2023-09-29 14:30:24,360 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2023-09-29 14:30:24,360 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2023-09-29 14:30:24,362 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2023-09-29 14:30:24,362 - util.py[DEBUG]: Read 34 bytes from /run/cloud-init/cloud.cfg
2023-09-29 14:30:24,362 - util.py[DEBUG]: Attempting to load yaml from string of length 34 with allowed root types (<class 'dict'>,)
2023-09-29 14:30:24,363 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2023-09-29 14:30:24,363 - util.py[DEBUG]: loaded blob returned None, returning default.
2023-09-29 14:30:24,363 - util.py[DEBUG]: Redirecting <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> to | tee -a /var/log/cloud-init-output.log
2023-09-29 14:30:24,367 - util.py[DEBUG]: Redirecting <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'> to | tee -a /var/log/cloud-init-output.log
2023-09-29 14:30:24,368 - main.py[DEBUG]: Logging being reset, this logger may no longer be active shortly
Cloud-init v. 23.3.daily-202309271631-d9cdc298~ubuntu20.04.1 running 'init-local' at Fri, 29 Sep 2023 14:30:24 +0000. Up 7983.77 seconds.
2023-09-29 14:30:26,414 - util.py[WARNING]: Failed to get guestinfo value for key metadata.encoding: Unexpected error while running command.
Command: ['/usr/bin/vmtoolsd', '--cmd', 'info-get guestinfo.metadata.encoding']
Exit code: 1
Reason: -
Stdout:
Stderr: Permission denied
2023-09-29 14:30:26,417 - util.py[WARNING]: Failed to query guestinfo with /usr/bin/vmtoolsd: Unexpected error while running command.
Command: ['/usr/bin/vmtoolsd', '--cmd', 'info-get guestinfo.metadata.encoding']
Exit code: 1
Reason: -
Stdout:
Stderr: Permission denied
2023-09-29 14:30:41,437 - DataSourceVMware.py[ERROR]: failed to find a valid data access method

------------------------------------------------------------------------------------------------
cloud-init.log:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceVMware.py", line 370, in get_guestinfo_data_fn
    return query_guestinfo(self.rpctool, self.rpctool_fn)
  File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceVMware.py", line 362, in query_guestinfo
    md = guestinfo("metadata", rpctool, rpctool_fn)
  File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceVMware.py", line 593, in guestinfo
    enc_type = guestinfo_get_value(key + ".encoding", rpctool, rpctool_fn)
  File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceVMware.py", line 627, in guestinfo_get_value
    raise error
  File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceVMware.py", line 604, in guestinfo_get_value
    (stdout, stderr) = rpctool_fn(
  File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceVMware.py", line 581, in exec_vmtoolsd
    (stdout, stderr) = subp([rpctool, "--cmd", arg])
  File "/usr/lib/python3/dist-packages/cloudinit/subp.py", line 322, in subp
    raise ProcessExecutionError(
cloudinit.subp.ProcessExecutionError: Unexpected error while running command.
Command: ['/usr/bin/vmtoolsd', '--cmd', 'info-get guestinfo.metadata.encoding']

root@vm:/var/log# python3 -c 'from cloudinit.subp import subp; rpctool, arg = "/usr/bin/vmtoolsd", "info-get guestinfo.metadata.encoding"; (stdout, stderr) = subp([rpctool, "--cmd", arg]); print(f"{stdout}|{stderr}")'
base64
|
```

**Comment by playerla** [comment]
Fix with upgrading open-vm-tools https://github.com/vmware/open-vm-tools/issues/692
