### ISSUE TITLE
Enabling a service with Ubuntu Pro/Advantage fails

### ISSUE THREAD

**Issue by WizardBit** [canonical/cloud-init#4491]
# Bug report

An error occurs when attaching an Ubuntu Pro/Advantage token with cloud-init and specifying the service to enable. The token does attach successfully, but does not enable the service.

## Steps to reproduce the problem

```
#cloud-config
ubuntu_advantage:
  token: <token>
  enable:
    - fips
```
The bug is because of `--` in the following command.
`ua enable --assume-yes --format -- json esm-apps esm-infra`
Output:
```
usage: pro enable <service> [<service>] [flags]
the following arguments are required: service
```

## Environment details
- Cloud-init version: 23.2.2-0ubuntu0~20.04.1
- Operating System Distribution: Ubuntu
- Cloud provider, platform or installer type: LXD

## cloud-init logs

```
2023-10-05 19:59:58,899 - cc_ubuntu_advantage.py[DEBUG]: Attaching to Ubuntu Advantage. ua attach --no-auto-enable REDACTED
2023-10-05 19:59:58,899 - subp.py[DEBUG]: Running hidden command to protect sensitive input/output logstring: ['ua', 'attach', '--no-auto-enable', 'REDACTED']
2023-10-05 20:00:03,786 - subp.py[DEBUG]: Running command ['ua', 'enable', '--assume-yes', '--format', 'json', '--', 'fips'] with allowed return codes {0, 1} (shell=False, capture=True)
2023-10-05 20:00:04,111 - handlers.py[DEBUG]: finish: modules-config/config-ubuntu-advantage: FAIL: running config-ubuntu-advantage with frequency once-per-instance
2023-10-05 20:00:04,111 - util.py[WARNING]: Running module ubuntu-advantage (<module 'cloudinit.config.cc_ubuntu_advantage' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ubuntu_advantage.py'>) failed
2023-10-05 20:00:04,111 - util.py[DEBUG]: Running module ubuntu-advantage (<module 'cloudinit.config.cc_ubuntu_advantage' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ubuntu_advantage.py'>) failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_ubuntu_advantage.py", line 302, in configure_ua
    enable_stdout, _ = subp.subp(cmd, capture=True, rcs={0, 1})
  File "/usr/lib/python3/dist-packages/cloudinit/subp.py", line 335, in subp
    raise ProcessExecutionError(
cloudinit.subp.ProcessExecutionError: Unexpected error while running command.
Command: ['ua', 'enable', '--assume-yes', '--format', 'json', '--', 'fips']
Exit code: 2
Reason: -
Stdout: 
Stderr: usage: pro enable <service> [<service>] [flags]
        the following arguments are required: service

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/config/modules.py", line 256, in _run_modules
    ran, _r = cc.run(
  File "/usr/lib/python3/dist-packages/cloudinit/cloud.py", line 67, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
  File "/usr/lib/python3/dist-packages/cloudinit/helpers.py", line 172, in run
    results = functor(**args)
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_ubuntu_advantage.py", line 521, in handle
    _attach(ua_section)
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_ubuntu_advantage.py", line 425, in _attach
    configure_ua(token=token, enable=ua_section.get("enable"))
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_ubuntu_advantage.py", line 304, in configure_ua
    raise RuntimeError(
RuntimeError: Error while enabling service(s): fips
```

**Comment by blackboxsw** [comment]
I can confirm this failure on Jammy with our integration tests: I also can confirm our jenkins setup automatically skipped this integration tests because of misconfigured environment that didn't provide CLOUD_INIT_UA_TOKEN to the integration test  runner. We'll fix both quickly thank you for filing this issue.
```
CLOUD_INIT_UA_TOKEN=REDACTED CLOUD_INIT_OS_IMAGE=jammy .tox/integration-tests/bin/pytest tests/integration_tests/modules/test_ubuntu_advantage.py::TestUbuntuAdvantage::test_idempotency
```
