### ISSUE TITLE
Growpart integration test intermittently failing

### ISSUE THREAD

**Issue by TheRealFalcon** [canonical/cloud-init#4613]
I can reproduce this both on 23.3 and on a daily install, so this doesn't represent a regression in 23.4.

# Bug report
[test_growpart](https://github.com/canonical/cloud-init/blob/main/tests/integration_tests/modules/test_growpart.py#L60) will intermittently fail locally and on jenkins.

Relevant logs from /var/log/cloud-init.log:
```
2023-11-20 20:56:58,924 - modules.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/pyt
hon3/dist-packages/cloudinit/config/cc_growpart.py'>) with frequency always
2023-11-20 20:56:58,924 - handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency alway
s
2023-11-20 20:56:58,924 - helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7fa96
e863b50>)
2023-11-20 20:56:58,924 - subp.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, ca
pture=True)
2023-11-20 20:56:58,927 - util.py[DEBUG]: Reading from /proc/517/mountinfo (quiet=False)
2023-11-20 20:56:58,928 - util.py[DEBUG]: Read 3422 bytes from /proc/517/mountinfo
2023-11-20 20:56:58,928 - util.py[DEBUG]: Reading from /sys/class/block/sda1/partition (quiet=False)
2023-11-20 20:56:58,928 - util.py[DEBUG]: Read 2 bytes from /sys/class/block/sda1/partition
2023-11-20 20:56:58,928 - util.py[DEBUG]: Reading from /sys/devices/pci0000:00/0000:00:01.1/0000:02:00.0/virtio6/host0/target0:
0:0/0:0:0:1/block/sda/dev (quiet=False)
2023-11-20 20:56:58,928 - util.py[DEBUG]: Read 4 bytes from /sys/devices/pci0000:00/0000:00:01.1/0000:02:00.0/virtio6/host0/tar
get0:0:0/0:0:0:1/block/sda/dev
2023-11-20 20:56:58,928 - util.py[DEBUG]: Reading from /proc/517/mountinfo (quiet=False)
2023-11-20 20:56:58,928 - util.py[DEBUG]: Read 3422 bytes from /proc/517/mountinfo
2023-11-20 20:56:58,928 - util.py[DEBUG]: Reading from /proc/517/mountinfo (quiet=False)
2023-11-20 20:56:58,928 - util.py[DEBUG]: Read 3422 bytes from /proc/517/mountinfo
2023-11-20 20:56:58,928 - subp.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/sda', '1'] with allowed return codes [0] (shell=False, capture=True)
2023-11-20 20:56:58,951 - util.py[DEBUG]: Reading from /sys/class/block/sdb1/partition (quiet=False)
2023-11-20 20:56:58,956 - util.py[DEBUG]: Read 2 bytes from /sys/class/block/sdb1/partition
2023-11-20 20:56:58,956 - util.py[DEBUG]: Reading from /sys/devices/pci0000:00/0000:00:01.1/0000:02:00.0/virtio6/host0/target0:0:1/0:0:1:1/block/sdb/dev (quiet=False)
2023-11-20 20:56:58,956 - util.py[DEBUG]: Read 5 bytes from /sys/devices/pci0000:00/0000:00:01.1/0000:02:00.0/virtio6/host0/target0:0:1/0:0:1:1/block/sdb/dev
2023-11-20 20:56:58,956 - util.py[DEBUG]: Reading from /proc/517/mountinfo (quiet=False)
2023-11-20 20:56:58,956 - util.py[DEBUG]: Read 3422 bytes from /proc/517/mountinfo
2023-11-20 20:56:58,956 - util.py[DEBUG]: Reading from /proc/517/mountinfo (quiet=False)
2023-11-20 20:56:58,956 - util.py[DEBUG]: Read 3422 bytes from /proc/517/mountinfo
2023-11-20 20:56:58,956 - subp.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/sdb', '1'] with allowed return codes [0] (shell=False, capture=True)
2023-11-20 20:56:58,975 - subp.py[DEBUG]: Running command ['growpart', '/dev/sdb', '1'] with allowed return codes [0] (shell=False, capture=True)
2023-11-20 20:56:59,288 - util.py[DEBUG]: resize_devices took 0.361 seconds
2023-11-20 20:56:59,289 - handlers.py[DEBUG]: finish: init-network/config-growpart: FAIL: running config-growpart with frequency always
2023-11-20 20:56:59,289 - util.py[WARNING]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_growpart.py'>) failed
2023-11-20 20:56:59,289 - util.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_growpart.py'>) failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/config/modules.py", line 255, in _run_modules
    ran, _r = cc.run(
  File "/usr/lib/python3/dist-packages/cloudinit/cloud.py", line 60, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
  File "/usr/lib/python3/dist-packages/cloudinit/helpers.py", line 172, in run
    results = functor(**args)
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_growpart.py", line 648, in handle
    resized = util.log_time(
  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 2831, in log_time
    ret = func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_growpart.py", line 574, in resize_devices
    (old, new) = resizer.resize(disk, ptnum, blockdev)
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_growpart.py", line 216, in resize
    return (before, get_size(partdev))
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_growpart.py", line 287, in get_size
    fd = os.open(filename, os.O_RDONLY)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/sdb1'
```

The strange this is that before getting this traceback, we can see that the block device exists. Furthermore, upon inspecting the VM after failure, it is seen by `blkid`:
```
root@cloudinit-1120-205633za62jife:~# lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0     7:0    0 40.9M  1 loop /snap/snapd/20290
loop1     7:1    0 63.5M  1 loop /snap/core20/2015
loop2     7:2    0 91.9M  1 loop /snap/lxd/24061
sda       8:0    0   10G  0 disk 
├─sda1    8:1    0  9.9G  0 part /
├─sda14   8:14   0    4M  0 part 
└─sda15   8:15   0  106M  0 part /boot/efi
sdb       8:16   0   16M  0 disk 
└─sdb1    8:17   0   16M  0 part 
```

I reproduced this using focal on an LXD VM.

**Comment by holmanb** [comment]
Interesting. Do we know when this first started failing?

**Comment by holmanb** [comment]
I have a couple of theories for a race that might cause this:

### Theory 1

1. `growpart` [closes the `flock`](https://github.com/canonical/cloud-utils/blob/6e6788e71654474d9c868d6cc942c91bc7ac6cdb/bin/growpart#L192) it has on `/dev/sdb1`
2. `growpart` immediately calls `udevadm settle` (line 193) which exits immediately since no udev event has been queued yet
3. `systemd-udevd` starts processing the event and the device file drops out briefly while cloud-init is checking the size of the device

> After the operation is complete the partitioner/formatter can simply close the device node. This has two effects: it implicitly releases the lock, so that systemd-udevd can process events on the device node again. Secondly, it results an IN_CLOSE_WRITE event, which causes systemd-udevd to immediately re-process the device — seeing all changes the tool made — and notify subscribed clients about it.

### Theory 2

One of `growpart`s' resizers forks a daemon - since daemons inherit open file descriptors, the '9' file descriptor remains open and `udevadm settle` is called before `systemd-udevd` gets the event.
> However, it should be noted that if an application unlocks a device after completing its work without closing it, i.e. while keeping the file descriptor open for further, longer time, then systemd-udevd will not notice this and not retrigger and thus reprobe the device.

### Resolution Options

Since the resize operation appears to have succeeded in your test output, I think this can be solved one of a couple different ways:

1. Assuming theory 1: Fix the race in `growpart`. How? Not sure. I don't see a synchronization method documented which would ensure that a call to `udevadm settle` won't return before `systemd-udevd` processes a new event.
2. Assuming theory 2: add a call to `flock --unlock` in `growpart:unlock_disk_and_settle()` - even if none of the resizers currently fork a daemon, it would be good defensive programming to do this anyways
3. Assuming either theory 1 or 2: retries getting the size should be safe in the case that this device previously existed and temporarily dropped due to systemd-udev processing
4. Assuming either theory 1 or 2: the only thing that this output is used for is user output - we could just eliminate the new size from the output and not worry about when udev actually processes the event
