### ISSUE TITLE
cloud-init uses NetworkManager to bring up interface failed when using sysconfig renderer

### ISSUE THREAD

**Issue by xiachen-rh** [canonical/cloud-init#4640]
# Bug report
Launching a RHEL instance in Aliyun, no local datasource is found in 'init-local' stage, so cloud-init runs  'init' stage to find the datasource and then configures network and brings up the interface, but it run the command failed.

## cloud-init logs
2023-11-27 20:25:31,020 - stages.py[INFO]: **Applying network configuration from ds bringup=True:** {'version': 2, 'ethernets': {'eth0': {'dhcp4': True, 'dhcp6': False, 'match': {'macaddress': '00:16:3e:35:a0:c0'}, 'set-name': 'eth0'}}}
**2023-11-27 20:25:31,023 - __init__.py[DEBUG]: Selected renderer 'sysconfig' from priority list: None**
2023-11-27 20:25:31,023 - util.py[DEBUG]: Reading from /sys/class/net/eth0/addr_assign_type (quiet=False)
2023-11-27 20:25:31,023 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/eth0/addr_assign_type
2023-11-27 20:25:31,023 - util.py[DEBUG]: Reading from /sys/class/net/eth0/uevent (quiet=False)
2023-11-27 20:25:31,024 - util.py[DEBUG]: Read 25 bytes from /sys/class/net/eth0/uevent
2023-11-27 20:25:31,024 - util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)
2023-11-27 20:25:31,024 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address
2023-11-27 20:25:31,024 - util.py[DEBUG]: Reading from /sys/class/net/eth0/device/device (quiet=False)
2023-11-27 20:25:31,024 - util.py[DEBUG]: Read 7 bytes from /sys/class/net/eth0/device/device
2023-11-27 20:25:31,024 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2023-11-27 20:25:31,024 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
2023-11-27 20:25:31,024 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2023-11-27 20:25:31,024 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
2023-11-27 20:25:31,024 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2023-11-27 20:25:31,024 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2023-11-27 20:25:31,024 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2023-11-27 20:25:31,024 - util.py[DEBUG]: Reading from /sys/class/net/eth0/type (quiet=False)
2023-11-27 20:25:31,024 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/eth0/type
2023-11-27 20:25:31,025 - util.py[DEBUG]: Reading from /sys/class/net/lo/type (quiet=False)
2023-11-27 20:25:31,025 - util.py[DEBUG]: Read 4 bytes from /sys/class/net/lo/type
2023-11-27 20:25:31,025 - network_state.py[DEBUG]: v2(ethernets) -> v1(physical):
{'type': 'physical', 'mac_address': '00:16:3e:35:a0:c0', 'name': 'eth0', 'match': {'macaddress': '00:16:3e:35:a0:c0'}, 'subnets': [{'type': 'dhcp4'}]}
2023-11-27 20:25:31,027 - network_state.py[DEBUG]: v2_common: handling config:
{'eth0': {'dhcp4': True, 'dhcp6': False, 'match': {'macaddress': '00:16:3e:35:a0:c0'}, 'set-name': 'eth0'}}
2023-11-27 20:25:31,028 - util.py[DEBUG]: Writing to /etc/sysconfig/network-scripts/ifcfg-eth0 - wb: [644] 159 bytes
2023-11-27 20:25:31,029 - util.py[DEBUG]: Restoring selinux mode for /etc/sysconfig/network-scripts/ifcfg-eth0 (recursive=False)
2023-11-27 20:25:31,031 - util.py[DEBUG]: Restoring selinux mode for /etc/sysconfig/network-scripts/ifcfg-eth0 (recursive=False)
2023-11-27 20:25:31,031 - util.py[DEBUG]: Writing to /etc/udev/rules.d/70-persistent-net.rules - wb: [600] 96 bytes
2023-11-27 20:25:31,032 - util.py[DEBUG]: Restoring selinux mode for /etc/udev/rules.d/70-persistent-net.rules (recursive=False)
2023-11-27 20:25:31,033 - util.py[DEBUG]: Restoring selinux mode for /etc/udev/rules.d/70-persistent-net.rules (recursive=False)
2023-11-27 20:25:31,033 - util.py[DEBUG]: Reading from /etc/sysconfig/network (quiet=True)
2023-11-27 20:25:31,033 - util.py[DEBUG]: Read 102 bytes from /etc/sysconfig/network
2023-11-27 20:25:31,033 - util.py[DEBUG]: Writing to /etc/sysconfig/network - wb: [644] 102 bytes
2023-11-27 20:25:31,034 - util.py[DEBUG]: Restoring selinux mode for /etc/sysconfig/network (recursive=False)
2023-11-27 20:25:31,035 - util.py[DEBUG]: Restoring selinux mode for /etc/sysconfig/network (recursive=False)
2023-11-27 20:25:31,035 - __init__.py[DEBUG]: Bringing up newly configured network interfaces
2023-11-27 20:25:31,036 - subp.py[DEBUG]: Running command ['systemctl', 'is-enabled', 'NetworkManager.service'] with allowed return codes [0] (shell=False, capture=True)
2023-11-27 20:25:31,048 - activators.py[DEBUG]: Using selected activator: <class 'cloudinit.net.activators.NetworkManagerActivator'> from priority: ['eni', 'netplan', 'network-manager', 'networkd']
2023-11-27 20:25:31,049 - activators.py[DEBUG]: Attempting command ['nmcli', 'connection', 'load', '/etc/NetworkManager/system-connections/cloud-init-eth0.nmconnection'] for device eth0
2023-11-27 20:25:31,049 - subp.py[DEBUG]: Running command ['nmcli', 'connection', 'load', '/etc/NetworkManager/system-connections/cloud-init-eth0.nmconnection'] with allowed return codes [0] (shell=False, capture=True)
2023-11-27 20:25:31,073 - activators.py[DEBUG]: Attempting command ['nmcli', 'connection', 'up', 'filename', '/etc/NetworkManager/system-connections/cloud-init-eth0.nmconnection'] for device eth0
2023-11-27 20:25:31,074 - subp.py[DEBUG]: Running command ['nmcli', 'connection', 'up', 'filename', '/etc/NetworkManager/system-connections/cloud-init-eth0.nmconnection'] with allowed return codes [0] (shell=False, capture=True)
**2023-11-27 20:25:31,091 - util.py[WARNING]: Running interface command ['nmcli', 'connection', 'up', 'filename', '/etc/NetworkManager/system-connections/cloud-init-eth0.nmconnection'] failed
2023-11-27 20:25:31,092 - util.py[DEBUG]: Running interface command ['nmcli', 'connection', 'up', 'filename', '/etc/NetworkManager/system-connections/cloud-init-eth0.nmconnection'] failed
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cloudinit/net/activators.py", line 23, in _alter_interface
    (_out, err) = subp.subp(cmd)
  File "/usr/lib/python3.6/site-packages/cloudinit/subp.py", line 336, in subp
    stdout=out, stderr=err, exit_code=rc, cmd=args
cloudinit.subp.ProcessExecutionError: Unexpected error while running command.**
Command: ['nmcli', 'connection', 'up', 'filename', '/etc/NetworkManager/system-connections/cloud-init-eth0.nmconnection']
Exit code: 10
Reason: -
Stdout: 
Stderr: Error: unknown connection '/etc/NetworkManager/system-connections/cloud-init-eth0.nmconnection'.
2023-11-27 20:25:31,106 - handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource
2023-11-27 20:25:31,107 - handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource

## Cause
The issue was introduced by this PR https://github.com/canonical/cloud-init/pull/1224

```
class NetworkManagerActivator(NetworkActivator):
    @staticmethod
    def available(target=None) -> bool:
        """Return true if network manager can be used on this system."""
        config_present = os.path.isfile(
            subp.target_path(target, path=NM_CFG_FILE)
        )
        nmcli_present = subp.which("nmcli", target=target)
        return config_present and bool(nmcli_present)
        """Return true if NetworkManager can be used on this system."""
        return nm_available(target=target)

    @staticmethod
    def bring_up_interface(device_name: str) -> bool:
        """Bring up interface using nmcli.
        """Bring up connection using nmcli.
        Return True is successful, otherwise return False
        """
        cmd = ["nmcli", "connection", "up", "ifname", device_name]
        from cloudinit.net.network_manager import conn_filename

        filename = conn_filename(device_name)
        cmd = ["nmcli", "connection", "load", filename]
        if _alter_interface(cmd, device_name):
            cmd = ["nmcli", "connection", "up", "filename", filename]
        else:
            _alter_interface(["nmcli", "connection", "reload"], device_name)
            cmd = ["nmcli", "connection", "up", "ifname", device_name]
        return _alter_interface(cmd, device_name)

``` 

Before the change, NetworkManger brought up interface via nmcli command with device_name, that's no problem.
```
cmd = ["nmcli", "connection", "up", "ifname", device_name]
```

After the change,  it uses nmcli command with filename but load the wrong configuration file /etc/NetworkManager/system-connections/cloud-init-eth0.nmconnection for sysconfig renderer, the configuration file is /etc/sysconfig/network-scripts/ifcfg-eth0. so it failed to run the command.

```
cmd = ["nmcli", "connection", "up", "filename", filename]
```

## Environment details
- Cloud-init version: 23.1.1
- Operating System Distribution: rhel
- Cloud provider, platform or installer type: Aliyun,  and this problem could also show out on other cloud platforms (AWS, OpenStack) when unexpected error happens in  'init-local' stage to lead to "No local datasource found",  and cloud-init looks for datasource in 'init' stage and brings up the interface which is configured by sysconfig renderer.

**Comment by ani-sinha** [comment]
Why is it using Network Manager Activator?

```
2023-11-27 20:25:31,048 - activators.py[DEBUG]: Using selected activator: <class 'cloudinit.net.activators.NetworkManagerActivator'> from priority: ['eni', 'netplan', 'network-manager', 'networkd']
```

I think it should use eni and this function is returning False

```
def available(target=None):
    expected = ["ifquery", "ifup", "ifdown"]
    search = ["/sbin", "/usr/sbin"]
    for p in expected:
        if not subp.which(p, search=search, target=target):
            return False
    eni = subp.target_path(target, "etc/network/interfaces")
    if not os.path.isfile(eni):
        return False

    return True
```
Perhaps a package that installs ifquery, ifup and ifdown is missing?

**Comment by ani-sinha** [comment]
The bug description spells out the inconsistency :
```
After the change, it uses nmcli command with filename but load the wrong configuration file /etc/NetworkManager/system-connections/cloud-init-eth0.nmconnection for sysconfig renderer, the configuration file should be /etc/sysconfig/network-scripts/ifcfg-eth0. so it failed to run the command.
```

**Comment by ani-sinha** [comment]
> Perhaps a package that installs ifquery, ifup and ifdown is missing?

Seems those scripts were missing all along. After investigation, I have sent PR #4645 as a potential fix to this issue.
