### ISSUE TITLE
cloud-init analyze needs better error handling

### ISSUE THREAD

**Issue by CodeBleu** [canonical/cloud-init#4686]
# Bug report

## Steps to reproduce the problem

Running ```cloud-init analyze show``` when cloud-init logs files are 0 bytes in size, it errors out with the following:
```
Traceback (most recent call last):
  File "/usr/local/bin/cloud-init", line 33, in <module>
    sys.exit(load_entry_point('cloud-init==23.4+31.g75ee2f07', 'console_scripts', 'cloud-init')())
  File "/usr/local/lib/python3.10/site-packages/cloud_init-23.4+31.g75ee2f07-py3.10.egg/cloudinit/cmd/main.py", line 1127, in main
    retval = util.log_time(
  File "/usr/local/lib/python3.10/site-packages/cloud_init-23.4+31.g75ee2f07-py3.10.egg/cloudinit/util.py", line 2814, in log_time
    ret = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/cloud_init-23.4+31.g75ee2f07-py3.10.egg/cloudinit/analyze/__init__.py", line 248, in analyze_show
    show.show_events(_get_events(infh), args.print_format)
  File "/usr/local/lib/python3.10/site-packages/cloud_init-23.4+31.g75ee2f07-py3.10.egg/cloudinit/analyze/__init__.py", line 274, in _get_events
    events, _ = dump.dump_events(rawdata=rawdata)
  File "/usr/local/lib/python3.10/site-packages/cloud_init-23.4+31.g75ee2f07-py3.10.egg/cloudinit/analyze/dump.py", line 160, in dump_events
    raise ValueError("Either cisource or rawdata parameters are required")
ValueError: Either cisource or rawdata parameters are required
```

## Environment details
- Cloud-init version: 23.4
- Operating System Distribution: OpenBSD
- Cloud provider, platform or installer type:

**Comment by holmanb** [comment]
Thanks for the report @CodeBleu. In this case I think that we would prefer output/rc closer to:
```
# cloud-init analyze show
Empty file /var/log/cloud-init.log
# echo $?
1
```

**Comment by AliyevH** [comment]
What about to function to check file content before dumping events and exiting with message and rc you mentioned ?

https://github.com/canonical/cloud-init/blob/928e79029c0d22b629418db666eec7fa270653ad/cloudinit/analyze/__init__.py#L273

**Comment by AliyevH** [comment]
@holmanb 
What about to check data and exit with rc and message you mentioned ?

https://github.com/canonical/cloud-init/blob/928e79029c0d22b629418db666eec7fa270653ad/cloudinit/analyze/show.py#L372
