### ISSUE TITLE
bootcmd results in python exit code: 127 "file not found error" 

### ISSUE THREAD

**Issue by jsikarin** [canonical/cloud-init#4716]
Bug report

bootcmd result in an error 127 code
Steps to reproduce the problem

    bootcmd
    - [ "cloud-init-per", "instance", "rm", "-f", "/etc/sudoers.d/*" ]

Environment details

    Cloud-init version: currently cloud-init 23.1.1-10.el8
    Operating System Distribution: RHEL 8
    Cloud provider, platform or installer type: AWS

cloud-init logs

2023-12-22 21:41:02,287 - subp.py[DEBUG]: Running command ['/bin/sh', '/run/cloud-init/tmp/tmp8rl75ydb.sh'] with allowed return codes [0] (shell=False, capture=False)
2023-12-22 21:41:02,310 - util.py[WARNING]: Failed to run bootcmd module bootcmd
2023-12-22 21:41:02,310 - util.py[DEBUG]: Failed to run bootcmd module bootcmd
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/cloudinit/config/cc_bootcmd.py", line 91, in handle
subp.subp(cmd, env=env, capture=False)
File "/usr/lib/python3.6/site-packages/cloudinit/subp.py", line 336, in subp
stdout=out, stderr=err, exit_code=rc, cmd=args
cloudinit.subp.ProcessExecutionError: Unexpected error while running command.
Command: ['/bin/sh', '/run/cloud-init/tmp/tmp8rl75ydb.sh']
Exit code: 127
Reason: -
Stdout: -
Stderr: -
2023-12-22 21:41:02,313 - handlers.py[DEBUG]: finish: init-network/config-bootcmd: FAIL: running config-bootcmd with frequency always

**Comment by jsikarin** [comment]
# Bug report


## Steps to reproduce the problem


## Environment details
- Cloud-init version: currently unknown will provide later
- Operating System Distribution: RHEL 8
- Cloud provider, platform or installer type: AWS

## cloud-init logs

**Comment by jsikarin** [comment]
# Bug report
 bootcmd result in an error 127 code 

## Steps to reproduce the problem
- bootcmd
       - [ "cloud-init-per", "instance", "rm", "-f", "/etc/sudoers.d/*" ]

## Environment details
- Cloud-init version: currently unknown will provide later
- Operating System Distribution: RHEL 8
- Cloud provider, platform or installer type: AWS

## cloud-init logs
2023-12-22 21:41:02,287 - subp.py[DEBUG]: Running command ['/bin/sh', '/run/cloud-init/tmp/tmp8rl75ydb.sh'] with allowed return codes [0] (shell=False, capture=False)
2023-12-22 21:41:02,310 - util.py[WARNING]: Failed to run bootcmd module bootcmd
2023-12-22 21:41:02,310 - util.py[DEBUG]: Failed to run bootcmd module bootcmd
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cloudinit/config/cc_bootcmd.py", line 91, in handle
    subp.subp(cmd, env=env, capture=False)
  File "/usr/lib/python3.6/site-packages/cloudinit/subp.py", line 336, in subp
    stdout=out, stderr=err, exit_code=rc, cmd=args
cloudinit.subp.ProcessExecutionError: Unexpected error while running command.
Command: ['/bin/sh', '/run/cloud-init/tmp/tmp8rl75ydb.sh']
Exit code: 127
Reason: -
Stdout: -
Stderr: -
2023-12-22 21:41:02,313 - handlers.py[DEBUG]: finish: init-network/config-bootcmd: FAIL: running config-bootcmd with frequency always

**Comment by dermotbradley** [comment]
It appears the user-data you are passing is incorrect. Running "cloud-init-per --help" manually indicates that the 2nd argument is "name", in your case the value "rm"is being used as the name rather than as the "cmd".

It should instead be:

```
bootcmd
- [ "cloud-init-per", "instance", "whatevername", "rm", "-f", "/etc/sudoers.d/*" ]
```

**Comment by TheRealFalcon** [comment]
As dermotbradley said, the command being used here is invalid. I'm going to close this issue, but if there's something we're missing, please do comment and we can re-open the issue.

**Comment by jsikarin** [comment]
The syntax may have been incorrect, but we only fixed the issue by switching from the latest version of cloud-init to 23.1.1-10.el8
