### ISSUE TITLE
Can no longer specify package names ending with a hyphen to suppress apt installation of transitive package dependencies

### ISSUE THREAD

**Issue by norrisjeremy** [canonical/cloud-init#5066]
# Bug report
We can no longer specify package names ending with a hyphen to prevent apt installation of transitive package dependencies.
Package names ending with a hyphen are now incorrectly interpreted as being `snap` packages (even when specified below the `apt` key) and are not passed to the `apt-get install` command.

For example, one can execute `apt-get install docker.io pigz- ubuntu-fan-` and `apt-get` will install `docker.io` without installing the optional recommended dependencies `pigz` & `ubuntu-fan`.

It used to be possible to utilize this syntax in cloud-init when specifying package names for the `cc_package_update_upgrade_install` module, but it appears this capability has been lost somehow.

## Steps to reproduce the problem

```
#cc_package_update_upgrade_install
package_update: True
package_upgrade: True
package_reboot_if_required: False
packages:
  - apt:
    - acl
    - apticron
    - debconf-utils
    - etckeeper
    - fail2ban
    - git
    - jq
    - logwatch
    - net-tools
    - nvme-cli
    - scsitools
    - sysstat
    - traceroute
    - unzip
    - zip
    - zsh
    - docker.io
    - pigz-
    - ubuntu-fan-
```

## Environment details
- Cloud-init version: `23.4.4-0ubuntu0~22.04.1`
- Operating System Distribution: `Ubuntu 22.04`
- Cloud provider, platform or installer type: `https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img`

## cloud-init logs

```
2024-03-18 13:38:03,074 - modules.py[DEBUG]: Running module package_update_upgrade_install (<module 'cloudinit.config.cc_package_update_upgrade_install' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_package_update_upgrade_install.py'>) with frequency once-per-instance
2024-03-18 13:38:03,074 - handlers.py[DEBUG]: start: modules-final/config-package_update_upgrade_install: running config-package_update_upgrade_install with frequency once-per-instance
2024-03-18 13:38:03,075 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/<omitted>/sem/config_package_update_upgrade_install - wb: [644] 24 bytes
2024-03-18 13:38:03,075 - helpers.py[DEBUG]: Running config-package_update_upgrade_install using lock (<FileLock using file '/var/lib/cloud/instances/<omitted>/sem/config_package_update_upgrade_install'>)
2024-03-18 13:38:03,075 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/<omitted>/sem/update_sources - wb: [644] 25 bytes
2024-03-18 13:38:03,075 - helpers.py[DEBUG]: Running update-sources using lock (<FileLock using file '/var/lib/cloud/instances/<omitted>/sem/update_sources'>)
2024-03-18 13:38:03,075 - apt.py[DEBUG]: Waiting for APT lock
2024-03-18 13:38:03,076 - apt.py[DEBUG]: APT lock available
2024-03-18 13:38:03,076 - subp.py[DEBUG]: Running command ['eatmydata', 'apt-get', '--option=Dpkg::Options::=--force-confold', '--option=Dpkg::options::=--force-unsafe-io', '--assume-yes', '--quiet', 'update'] with allowed return codes [0] (shell=False, capture=False)
2024-03-18 13:38:13,515 - util.py[DEBUG]: apt-update [eatmydata apt-get --option=Dpkg::Options::=--force-confold --option=Dpkg::options::=--force-unsafe-io --assume-yes --quiet update] took 10.439 seconds
2024-03-18 13:38:13,515 - apt.py[DEBUG]: Waiting for APT lock
2024-03-18 13:38:13,515 - apt.py[DEBUG]: APT lock available
2024-03-18 13:38:13,515 - subp.py[DEBUG]: Running command ['eatmydata', 'apt-get', '--option=Dpkg::Options::=--force-confold', '--option=Dpkg::options::=--force-unsafe-io', '--assume-yes', '--quiet', 'dist-upgrade'] with allowed return codes [0] (shell=False, capture=False)
2024-03-18 13:38:25,423 - util.py[DEBUG]: apt-dist-upgrade [eatmydata apt-get --option=Dpkg::Options::=--force-confold --option=Dpkg::options::=--force-unsafe-io --assume-yes --quiet dist-upgrade] took 11.908 seconds
2024-03-18 13:38:25,423 - subp.py[DEBUG]: Running command ['snap', 'refresh'] with allowed return codes [0] (shell=False, capture=True)
2024-03-18 13:38:26,802 - helpers.py[DEBUG]: update-sources already ran (freq=once-per-instance)
2024-03-18 13:38:26,802 - subp.py[DEBUG]: Running command ['apt-cache', 'pkgnames'] with allowed return codes [0] (shell=False, capture=True)
2024-03-18 13:38:26,911 - apt.py[DEBUG]: The following packages were not found by APT so APT will not attempt to install them: ['ubuntu-fan-', 'pigz-']
2024-03-18 13:38:26,911 - apt.py[DEBUG]: Waiting for APT lock
2024-03-18 13:38:26,912 - apt.py[DEBUG]: APT lock available
2024-03-18 13:38:26,912 - subp.py[DEBUG]: Running command ['eatmydata', 'apt-get', '--option=Dpkg::Options::=--force-confold', '--option=Dpkg::options::=--force-unsafe-io', '--assume-yes', '--quiet', 'install', 'zsh', 'debconf-utils', 'jq', 'apticron', 'logwatch', 'traceroute', 'sysstat', 'zip', 'acl', 'git', 'etckee
per', 'nvme-cli', 'docker.io', 'net-tools', 'unzip', 'fail2ban', 'scsitools'] with allowed return codes [0] (shell=False, capture=False)
2024-03-18 13:39:03,627 - util.py[DEBUG]: apt-install [eatmydata apt-get --option=Dpkg::Options::=--force-confold --option=Dpkg::options::=--force-unsafe-io --assume-yes --quiet install zsh debconf-utils jq apticron logwatch traceroute sysstat zip acl git etckeeper nvme-cli docker.io net-tools unzip fail2ban scsitool
s] took 36.716 seconds
2024-03-18 13:39:03,627 - __init__.py[INFO]: Failed to install the following packages: {'pigz-', 'ubuntu-fan-'}. See associated package manager logs for more details.
2024-03-18 13:39:03,628 - subp.py[DEBUG]: Running command ['snap', 'install', 'pigz-'] with allowed return codes [0] (shell=False, capture=True)
2024-03-18 13:39:03,642 - snap.py[INFO]: Failed to 'snap install pigz-'!
2024-03-18 13:39:03,642 - subp.py[DEBUG]: Running command ['snap', 'install', 'ubuntu-fan-'] with allowed return codes [0] (shell=False, capture=True)
2024-03-18 13:39:03,656 - snap.py[INFO]: Failed to 'snap install ubuntu-fan-'!
2024-03-18 13:39:03,656 - util.py[WARNING]: Failed to install packages: [{'apt': ['acl', 'apticron', 'debconf-utils', 'etckeeper', 'fail2ban', 'git', 'jq', 'logwatch', 'net-tools', 'nvme-cli', 'scsitools', 'sysstat', 'traceroute', 'unzip', 'zip', 'zsh', 'docker.io', 'pigz-', 'ubuntu-fan-']}]
2024-03-18 13:39:03,656 - util.py[DEBUG]: Failed to install packages: [{'apt': ['acl', 'apticron', 'debconf-utils', 'etckeeper', 'fail2ban', 'git', 'jq', 'logwatch', 'net-tools', 'nvme-cli', 'scsitools', 'sysstat', 'traceroute', 'unzip', 'zip', 'zsh', 'docker.io', 'pigz-', 'ubuntu-fan-']}]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_package_update_upgrade_install.py", line 121, in handle
    cloud.distro.install_packages(pkglist)
  File "/usr/lib/python3/dist-packages/cloudinit/distros/__init__.py", line 260, in install_packages
    raise PackageInstallerError(error_message % uninstalled)
cloudinit.distros.PackageInstallerError: Failed to install the following packages: ['pigz-', 'ubuntu-fan-']. See associated package manager logs for more details.
2024-03-18 13:39:03,659 - cc_package_update_upgrade_install.py[WARNING]: 1 failed with exceptions, re-raising the last one
2024-03-18 13:39:03,659 - handlers.py[DEBUG]: finish: modules-final/config-package_update_upgrade_install: FAIL: running config-package_update_upgrade_install with frequency once-per-instance
2024-03-18 13:39:03,659 - util.py[WARNING]: Running module package_update_upgrade_install (<module 'cloudinit.config.cc_package_update_upgrade_install' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_package_update_upgrade_install.py'>) failed
2024-03-18 13:39:03,659 - util.py[DEBUG]: Running module package_update_upgrade_install (<module 'cloudinit.config.cc_package_update_upgrade_install' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_package_update_upgrade_install.py'>) failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/config/modules.py", line 255, in _run_modules
    ran, _r = cc.run(
  File "/usr/lib/python3/dist-packages/cloudinit/cloud.py", line 60, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
  File "/usr/lib/python3/dist-packages/cloudinit/helpers.py", line 172, in run
    results = functor(**args)
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_package_update_upgrade_install.py", line 147, in handle
    raise errors[-1]
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_package_update_upgrade_install.py", line 121, in handle
    cloud.distro.install_packages(pkglist)
  File "/usr/lib/python3/dist-packages/cloudinit/distros/__init__.py", line 260, in install_packages
    raise PackageInstallerError(error_message % uninstalled)
cloudinit.distros.PackageInstallerError: Failed to install the following packages: ['pigz-', 'ubuntu-fan-']. See associated package manager logs for more details.
```

**Comment by norrisjeremy** [comment]
FYI, I suspect something like the following may fix this issue:
```
diff --git a/cloudinit/distros/package_management/apt.py b/cloudinit/distros/package_management/apt.py
index 627c0348e..1250d4161 100644
--- a/cloudinit/distros/package_management/apt.py
+++ b/cloudinit/distros/package_management/apt.py
@@ -123,7 +123,7 @@ class Apt(PackageManager):
         return set(resp.splitlines())
 
     def get_unavailable_packages(self, pkglist: Iterable[str]):
-        return [pkg for pkg in pkglist if pkg not in self.get_all_packages()]
+        return [pkg for pkg in pkglist if pkg not in self.get_all_packages() and not pkg.endswith("-")]
 
     def install_packages(self, pkglist: Iterable) -> UninstalledPackages:
         self.update_package_sources()
```

**Comment by blackboxsw** [comment]
Thanks for filing this bug and improving cloud-init.
This is indeed an issue given the flexibility of that apt cmdline. We should address both the trailing minus to allow pkg removal as well as the `pkg_name/target_release` formats as well and we can put this into our next release as a high priority fix. I think something like the following diff should work. And I think we should add module documentation example to represent this behavior for others who may want to drive package removal via `packages` cloud-config directives.
```diff
--- a/cloudinit/distros/package_management/apt.py
+++ b/cloudinit/distros/package_management/apt.py
@@ -122,8 +122,17 @@ class Apt(PackageManager):
         # faster
         return set(resp.splitlines())
 
-    def get_unavailable_packages(self, pkglist: Iterable[str]):
-        return [pkg for pkg in pkglist if pkg not in self.get_all_packages()]
+    def get_unavailable_packages(
+        self, pkglist: Iterable[str]
+    ) -> Iterable[str]:
+        all_packages = self.get_all_packages()
+        unavailable_pkgs: Iterable[str] = []
+        for pkg in pkglist:
+            (pkg, _, target_release) = pkg.partition("/")
+            # Packages can be removed by apt install command with - suffix
+            if pkg.rstrip("-") not in all_packages:
+                unavailable_pkgs.append(pkg)
+        return unavailable_pkgs
 
     def install_packages(self, pkglist: Iterable) -> UninstalledPackages:
         self.update_package_sources()
```

**Comment by norrisjeremy** [comment]
Also, I found it unintuitive that cloud-init attempted to use `snap` to install package names that were explicitly listed under the `apt:` key.
Should the fallback behavior to try and use `snap` to resolve an unavailable package also be corrected in this case?

**Comment by TheRealFalcon** [comment]
> Should the fallback behavior to try and use snap to resolve an unavailable package also be corrected in this case?

Yes, that will be addressed as well

**Comment by norrisjeremy** [comment]
> > Should the fallback behavior to try and use snap to resolve an unavailable package also be corrected in this case?
> 
> Yes, that will be addressed as well

Great, thanks!
