### ISSUE TITLE
Traceback when running `cloud-init collect-logs` as non-root

### ISSUE THREAD

**Issue by TheRealFalcon** [canonical/cloud-init#5093]
While it is correct behavior to disallow access to root read-only files, we should emit a helpful error message rather than an ugly traceback.
```
nonroot@me:/tmp$ cloud-init collect-logs
version:  /usr/bin/cloud-init 24.1.2

Traceback (most recent call last):
  File "/usr/bin/cloud-init", line 33, in <module>
    sys.exit(load_entry_point('cloud-init==24.1', 'console_scripts', 'cloud-init')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 1138, in main
    retval = util.log_time(
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 2828, in log_time
    ret = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/devel/logs.py", line 296, in handle_collect_logs_args
    return collect_logs(args.tarfile, args.userdata, args.verbosity)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/devel/logs.py", line 255, in collect_logs
    _collect_file(log, log_dir, verbosity)
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/devel/logs.py", line 185, in _collect_file
    copy(path, out_dir)
  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 2094, in copy
    shutil.copy(src, dest)
  File "/usr/lib/python3.12/shutil.py", line 435, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.12/shutil.py", line 260, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/var/log/cloud-init.log'
nonroot@me:/tmp$ 
```

**Comment by holmanb** [comment]
@TheRealFalcon we typically try to handle errors like this at the callsite, which I think is typically appropriate, but do you think maybe some top level generic handlers in main.py might be useful to avoid errors like this?

**Comment by TheRealFalcon** [comment]
> do you think maybe some top level generic handlers in main.py might be useful to avoid errors like this?

Perhaps. At the top level they'd have to be generic enough to just spit out the error that's already at the bottom of the traceback, which I'm not sure is much more valuable. It'll make the output a little more pretty, but it's not adding any context for the user, and a generic message could make it harder to track down the source of the exception. I don't have strong opinions either way though.

**Comment by TheRealFalcon** [comment]
This was fixed in https://github.com/canonical/cloud-init/pull/5619
