### ISSUE TITLE
[docs]: Can't disable network config

### ISSUE THREAD

**Issue by russellshackleford** [canonical/cloud-init#5205]
# Documentation request

https://cloudinit.readthedocs.io/en/latest/reference/network-config.html#cloud-config
```
network:
  config: disabled
```

Appears to do nothing, am I missing something? My only goal is for cloud init to not touch networking in any fashion.

**Comment by holmanb** [comment]
Hey @russellshackleford, thanks for raising this issue.

> Appears to do nothing, am I missing something?

Can you please be more specific? Which changes are you attempting to prevent cloud-init from making? "All of them" is pretty broad, and in some cases cloud-init has to modify the instance's network in order to do things like get the user configuration.

> My only goal is for cloud init to not touch networking in any fashion.

Which platform are you trying to run this on and why are you trying to do this?

**Comment by russellshackleford** [comment]
Thanks for your quick reply. In short, networking is pre-baked into my company's images and an image is made for each of our cloud providers as well as for colocated and owned datacenters. With thousands of instances out there, the need for as much unification as possible is strong. That said, our only current use of cloud-init is growroot/growpart. We explicitly do not allow user-data, and the unified use of DHCP in all environments makes any networking configuration unnecessary. The current platform is alma 8 and indeed, even the systemd unit file only looks for `cloud-init=disabled` in the kernel command line, not `network-config=disabled` (though cmdline.py supposedly does). Either way, it is ineffective and continues to configure ipv4/6 and routes.

**Comment by holmanb** [comment]
> Thanks for your quick reply.

Happy to help.

> In short, networking is pre-baked into my company's images and an image is made for each of our cloud providers as well as for colocated and owned datacenters. With thousands of instances out there, the need for as much unification as possible is strong.

Great context, thanks. 

> That said, our only current use of cloud-init is growroot/growpart.

Interesting, good to know.

> We explicitly do not allow user-data, and the unified use of DHCP in all environments makes any networking configuration unnecessary.

Are you running your own dhcp server in cloud environments?

> The current platform is alma 8 and indeed, even the systemd unit file only looks for cloud-init=disabled in the kernel command line, not network-config=disabled (though cmdline.py supposedly does).

Note that including the cloud-init=disabled check in the service file disables **all** of cloud-init, not just networking. This would be the wrong place to disable cloud-init networking.

> Either way, it is ineffective and continues to configure ipv4/6 and routes.

This sounds like a possible bug in cloud-init. I think we're going to need a little more context to help you resolve this issue.

I suspect one of the following:

1) cloud-init is not correctly tearing down the ephemeral dhcp routes (maybe dhcpcd adds routes that cloud-init doesn't clean up)
2) cloud-init is for some reason writing network config somewhere?

If the routes are only in the kernel's routing table (not stored in configuration files on disk) then likely 1), otherwise 2).

Could you please provide logs? Either `sudo cloud-init collect-logs` (preferred) or at the minimum `/var/log/cloud-init.log` would go a long ways towards creating a reproducer and fix.

**Comment by russellshackleford** [comment]
> Are you running your own dhcp server in cloud environments?

Generally, no.

> Note that including the cloud-init=disabled check in the service file disables **all** of cloud-init, not just networking. This would be the wrong place to disable cloud-init networking.

I'm sorry, poor wording on my part. `network-config=disabled` came from https://cloudinit.readthedocs.io/en/latest/reference/network-config.html. I was only trying to disable any networking. I knew better than to disable all of cloud-init.

> This sounds like a possible bug in cloud-init. I think we're going to need a little more context to help you resolve this issue.
> 
> I suspect one of the following:
> 
>     1. cloud-init is not correctly tearing down the ephemeral dhcp routes (maybe dhcpcd adds routes that cloud-init doesn't clean up)
> 
>     2. cloud-init is for some reason writing network config somewhere?

It is known to be writing `/etc/sysconfig/network-scripts/ifcfg-eth0` on a host that is purely (or at least was) NetworkManager controlled.

> Could you please provide logs of an affected test system? The tarball created by `sudo cloud-init collect-logs` (preferred) or at the minimum a full `/var/log/cloud-init.log` would go a long ways towards creating a reproducer and a fix.

Picking through `/var/log/cloud-init.log` I found a traceback, which looks promising to fix:

```
2024-04-24 16:38:36,520 - util.py[WARNING]: failed stage init-local
2024-04-24 16:38:36,520 - util.py[DEBUG]: failed stage init-local
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cloudinit/cmd/main.py", line 767, in status_wrapper
    ret = functor(name, args)
  File "/usr/lib/python3.6/site-packages/cloudinit/cmd/main.py", line 433, in main_init
    init.apply_network_config(bring_up=bring_up_interfaces)
  File "/usr/lib/python3.6/site-packages/cloudinit/stages.py", line 938, in apply_network_config
    self.distro.networking.wait_for_physdevs(netcfg)
  File "/usr/lib/python3.6/site-packages/cloudinit/distros/networking.py", line 142, in wait_for_physdevs
    physdevs = self.extract_physdevs(netcfg)
  File "/usr/lib/python3.6/site-packages/cloudinit/distros/networking.py", line 46, in extract_physdevs
    return net.extract_physdevs(netcfg)
  File "/usr/lib/python3.6/site-packages/cloudinit/net/__init__.py", line 660, in extract_physdevs
    raise RuntimeError("Unknown network config version: %s" % version)
RuntimeError: Unknown network config version: None
```

`/etc/cloud/cloud.cfg` in its entirely with that traceback is
```
network:
  config: disable

allow_userdata: false
```

**Comment by russellshackleford** [comment]
The cfg should read `disabled`, not `disable`. That may have been the cause of the traceback. Testing...

**Comment by russellshackleford** [comment]
Just to be clear, prior to opening this issue, I was using the `disabled` option, not `disable`. I was not getting a traceback at that time. I also may have not been looking at the correct data points as I've just discovered potentially a better one and am building a new clean image for testing. Will post when I've dug more out.

**Comment by russellshackleford** [comment]
Ok, here is what I know:

1. `/etc/sysconfig/network-scripts/ifcfg-eth0` was previously being changed by cloud-init, but with so many runs and re-runs it is impossible to say under which version of the config file this had happened (this file is what I referred to above as my "better data point" along with every file in `/etc/NetworkManager`
2. If there is a better data point, there has to be a worse one. Namely, `cloud-init.log`. If cloud-init is not touching networking, then why would the log say it is running several `ip`, `dhclient`, and `hostnamectl` commands?
```
$ sudo grep 'Running command' /var/log/cloud-init.log 
2024-04-24 17:47:24,304 - subp.py[DEBUG]: Running command ['ip', 'link', 'set', 'dev', 'eth0', 'up'] with allowed return codes [0] (shell=False, capture=True)
2024-04-24 17:47:24,499 - subp.py[DEBUG]: Running command ['/usr/sbin/dhclient', '-1', '-v', '-lf', '/run/dhclient.lease', '-pf', '/run/dhclient.pid', 'eth0', '-sf', '/bin/true'] with allowed return codes [0] (shell=False, capture=True)
2024-04-24 17:47:24,776 - subp.py[DEBUG]: Running command ['ip', '-family', 'inet', 'addr', 'add', '10.0.27.51/19', 'broadcast', '10.0.31.255', 'dev', 'eth0'] with allowed return codes [0] (shell=False, capture=True)
2024-04-24 17:47:24,778 - subp.py[DEBUG]: Running command ['ip', '-family', 'inet', 'link', 'set', 'dev', 'eth0', 'up'] with allowed return codes [0] (shell=False, capture=True)
2024-04-24 17:47:24,780 - subp.py[DEBUG]: Running command ['ip', 'route', 'show', '0.0.0.0/0'] with allowed return codes [0] (shell=False, capture=True)
2024-04-24 17:47:24,782 - subp.py[DEBUG]: Running command ['ip', '-4', 'route', 'add', '10.0.0.1', 'dev', 'eth0', 'src', '10.0.27.51'] with allowed return codes [0] (shell=False, capture=True)
2024-04-24 17:47:24,784 - subp.py[DEBUG]: Running command ['ip', '-4', 'route', 'add', 'default', 'via', '10.0.0.1', 'dev', 'eth0'] with allowed return codes [0] (shell=False, capture=True)
2024-04-24 17:48:14,944 - subp.py[DEBUG]: Running command ['ip', '-4', 'route', 'del', 'default', 'dev', 'eth0'] with allowed return codes [0] (shell=False, capture=True)
2024-04-24 17:48:14,946 - subp.py[DEBUG]: Running command ['ip', '-4', 'route', 'del', '10.0.0.1', 'dev', 'eth0', 'src', '10.0.27.51'] with allowed return codes [0] (shell=False, capture=True)
2024-04-24 17:48:14,948 - subp.py[DEBUG]: Running command ['ip', '-family', 'inet', 'link', 'set', 'dev', 'eth0', 'down'] with allowed return codes [0] (shell=False, capture=True)
2024-04-24 17:48:14,953 - subp.py[DEBUG]: Running command ['ip', '-family', 'inet', 'addr', 'del', '10.0.27.51/19', 'dev', 'eth0'] with allowed return codes [0] (shell=False, capture=True)
2024-04-24 17:48:14,974 - subp.py[DEBUG]: Running command ['hostnamectl', 'set-hostname', 'ip-10-0-27-51.eu-west-1.compute.internal'] with allowed return codes [0] (shell=False, capture=True)
2024-04-24 17:48:15,051 - subp.py[DEBUG]: Running command ['hostname', 'ip-10-0-27-51.eu-west-1.compute.internal'] with allowed return codes [0] (shell=False, capture=True)
2024-04-24 17:48:15,731 - subp.py[DEBUG]: Running command ['ip', '--json', 'addr'] with allowed return codes [0] (shell=False, capture=True)
2024-04-24 17:48:15,735 - subp.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
2024-04-24 17:48:15,738 - subp.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
```

My system will get networking just fine without cloud-init, I'm just trying to get it to stop.

**Comment by dermotbradley** [comment]
You haven't indicated which DataSource(s) are being used.

> an image is made for each of our cloud providers as well as for colocated and owned datacenters

As @holmanb aluded to, ephemeral dhcp is typically used by many/most of the cloud provider DataSources (i.e. Ec2, Azure, GCE) in order to bring up temporary networking in order to contact the provider's Metadata Server to fetch meta-info, network-config, vendor-data, and user-data settings.

Generally speaking with cloud providers when you create a VM, whether using their web "console" or CLI or API, you would assign that new VM to a particular network subnet/VPC, perhaps give it a static IP address (or just use DHCP), and then the provider's Metadata server would make available "network-config" containing these relevant settings for cloud-init to fetch.

Without having logfiles to look at and/or more detailed information it will be hard for anyone to help you.

**Comment by holmanb** [comment]
Cloud-init modifies networking in two different ways: ephemeral networking and network configuration.

The network configuration part is what modifies network config files under `/etc/`, and that part is what is controlled by the `disabled` key. From your comments above, it sounds like  the tracebacks (and probably network configuration modification) were due to an invalid key? Please correct me if I misunderstood.

The ephemeral networking that @dermotbradley mentioned is used to get configuration from the clouds, and that is why cloud-init is running the `dhclient` and `ip commands`. It sounds like you don't need or want these. I don't think that a configuration key explicitly exists for this, but it would probably be possible to do this by forcing cloud-init to use a specific datasource which doesn't use ephemeral networking. Cloud-init has two generic datasources that give the user the ability to do more customization. Using them is a little more "hands on", since cloud-init normally tries to make networking (and datasource/cloud selection) "just work" by default. If you want to try using one of these datasources, which do not do ephemeral networking, you might try looking into the [NoCloud](https://cloudinit.readthedocs.io/en/latest/reference/datasources/nocloud.html) or [None](https://cloudinit.readthedocs.io/en/latest/reference/datasources/none.html) datasource docs. Datasource selection is done in `/etc/cloud/cloud.cfg` using a single-line `datasource_list: [list, of, datasources]`.

**Comment by russellshackleford** [comment]
As for the log, I posted the gist of cloud-init.log, but forgot to add a comment with a link. Apologies. As for the None datasource, that whittled it down to 3 invocations of `ip` all of which were gathering info, not changing anything, so it seems my goals have been met and I wish to heartily thank both of you. :tipping_hand_man:

**Comment by dermotbradley** [comment]
As a side note, for cloud providers like AWS, Azure, and GCP I assume that the network-config provided via their Metadata Server is **the authorative "source of truth" regarding the network configuration** for a particular VM, so ignoring it (by not using the Ec2 DataSource to fetch it & configure using it) and instead "blindly" always using DHCP and other hardcoded settings (not provided by DHCP options) could potentially be problematic. For example on a machine with multiple network interfaces a hardcoded DHCP client might run on the wrong interface...
