### ISSUE TITLE
AttributeError: module 'cloudinit.log' has no attribute 'getLogger' when running cloud-init init --local

### ISSUE THREAD

**Issue by TilGP** [canonical/cloud-init#5274]
# Bug report
I don't know how long this has been an issue, because I don't frequently look at the logs where this showed up.
My Ubuntu installation tries to start cloud-init-local.service, It produces the aforementioned error and exits with code 1.

I actually couldn't find the `DataSourceUI.py` in this repo for some reason, so I have attached it: [DataSourceUI.zip](https://github.com/canonical/cloud-init/files/15255346/DataSourceUI.zip)

## Steps to reproduce the problem

I have no idea

## Environment details
- Cloud-init version: 24.1.3-0ubuntu1~22.04.1
- Operating System Distribution: Ubuntu
- Cloud provider, platform or installer type: Ionos

## cloud-init logs
```
Cloud-init v. 24.1.3-0ubuntu1~22.04.1 running 'init-local' at Wed, 08 May 2024 21:16:50 +0000. Up 247.45 seconds.
2024-05-08 21:16:50,253 - util.py[WARNING]: failed stage init-local
failed run of stage init-local
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 781, in status_wrapper
    ret = functor(name, args)
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 394, in main_init
    init.fetch(existing=existing)
  File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 501, in fetch
    return self._get_data_source(existing=existing)
  File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 366, in _get_data_source
    (ds, dsname) = sources.find_source(
  File "/usr/lib/python3/dist-packages/cloudinit/sources/__init__.py", line 1012, in find_source
    ds_list = list_sources(cfg_list, ds_deps, pkg_list)
  File "/usr/lib/python3/dist-packages/cloudinit/sources/__init__.py", line 1059, in list_sources
    m_locs, _looked_locs = importer.find_module(
  File "/usr/lib/python3/dist-packages/cloudinit/importer.py", line 73, in find_module
    if _count_attrs(full_path, required_attrs) == len(required_attrs):
  File "/usr/lib/python3/dist-packages/cloudinit/importer.py", line 28, in _count_attrs
    mod = importlib.import_module(module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceUI.py", line 25, in <module>
    LOG = logging.getLogger(__name__)
AttributeError: module 'cloudinit.log' has no attribute 'getLogger'
```

**Comment by holmanb** [comment]
> # Bug report

Thanks for reporting this issue!

> I don't know how long this has been an issue, because I don't frequently look at the logs where this showed up. My Ubuntu installation tries to start cloud-init-local.service, It produces the aforementioned error and exits with code 1.

Uh oh. That shouldn't be happening.

> I actually couldn't find the `DataSourceUI.py` in this repo for some reason, so I have attached it: [DataSourceUI.zip](https://github.com/canonical/cloud-init/files/15255346/DataSourceUI.zip)

Huh, that's interesting. Looks like this was authored by Jorge Jimenez of United Internet.

> ## Environment details
> 
>     * Cloud-init version: 24.1.3-0ubuntu1~22.04.1
> 
>     * Operating System Distribution: Ubuntu
> 
>     * Cloud provider, platform or installer type: Ionos
> 

I haven't heard of Ionos before.

@TilGP So the good news is that the code fix is easy. The bad news is that I'm not sure who can fix it.

The file that threw this exception is not from upstream cloud-init. That's why you didn't find it in the repository. Cloud-init makes it easy for cloud providers to provide their own glue code for cloud-init to work on their cloud. However, when clouds make use of this capability and don't upstream their code, it is their responsibility to maintain that code, and sometimes the upstream changes change the module imports[1], which requires the cloud code maintainers to update their code. Code that gets contributed to this project gets updated for changes like this.

What happened is cloud-init recently made some changes to how logging works on cloud-init. This means that cloud-init no longer has a `getLogger()` in the `log` module. The fix should be simple, just import the Python module's `logging` module instead.

You'll need to reach out to whoever is maintaining this software to get them to fix it. I'm not sure whether Ionos or United Internet would be best.

[1] This is unfortunately something that upstream cloud-init cannot guarantee stability for. Given the permissive nature of Python imports there is simply no way of knowing which code clouds may or may not be using.

**Comment by holmanb** [comment]
@TilGP since this isn't a bug in upstream cloud-init I'm going to close this issue. Thanks again for filing this issue and good luck with getting whoever maintains `DataSourceUI.py` code to fix it.

**Comment by TilGP** [comment]
Thanks for the quick response,
I'll try to find, where my installation of cloud-init comes from and open an issue there.
Fyi ionos is a German (v-)server hosting provider that also offers prepackaged Linux images.

**Comment by holmanb** [comment]
> Thanks for the quick response, I'll try to find, where my installation of cloud-init comes from and open an issue there.

No problem, sounds good.

> Fyi ionos is a German (v-)server hosting provider that also offers prepackaged Linux images.

Good to know, thanks!
