### ISSUE TITLE
cloud-init network fails in ipv6-only subnet with multi-NICs (KeyError: 'subnet-ipv4-cidr-block')

### ISSUE THREAD

**Issue by leezu** [canonical/cloud-init#5283]
# Bug report
cloud-init network fails in ipv6-only subnet (KeyError: 'subnet-ipv4-cidr-block'). Instance has no connectivity after boot and needs to be accessed via EC2 Console. As cloud-init failed, no users and passwords are setup, and it's impossible to recover the instance.

cc: @blackboxsw as it's potentially a regression from https://github.com/canonical/cloud-init/pull/5071

## Steps to reproduce the problem
1. Configure VPC to enable IPv6 by clicking "Edit CIDRs" and associating an IPv6 CIDR
2. Create new subnet in VPC, specifying "No IPv4 CIDR" and selecting the IPv6 CIDR block. Specify availability zone of choice.
3. Launch **a multi-NIC** instance in the ipv6-only subnet. Make sure to pass `--metadata-options "HttpEndpoint=enabled,HttpTokens=required,HttpProtocolIpv6=enabled"` to enable the IPv6 IMDS endpoint and require IMDSv2.
4. Monitor instance boot through ec2-instance-connect serial console, eg. for us-west-2 at https://us-west-2.console.aws.amazon.com/ec2-instance-connect/ssh?region=us-west-2&connType=serial&instanceId=INSTANCE-ID&serialPort=0#/ where INSTANCE-ID is your instance-id.

## Environment details
- Cloud-init version: 24.1.3-0ubuntu3
- Operating System Distribution: ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-20240423
- Cloud provider, platform or installer type: AWS

## cloud-init logs
```
[   65.711562] cloud-init[1800]: 2024-05-12 13:04:20,819 - url_helper.py[WARNING]: Calling 'url ? None' failed [50/120s]: unexpected error [sequence item 0: expected str instance, UrlError found]
[   67.947784] cloud-init[1800]: 2024-05-12 13:04:23,056 - util.py[WARNING]: failed stage init-local
[   67.987120] cloud-init[1800]: failed run of stage init-local
[   68.011589] cloud-init[1800]: ------------------------------------------------------------
[FAILED] Failed to start cloud-init-local.s…al cloud-init job (pre-networking).
See 'systemctl status cloud-init-local.service' for details.
[   68.011683] cloud-init[1800]: Traceback (most recent call last):
[   68.153318] cloud-init[1800]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 774, in status_wrapper
[   68.153468] cloud-init[1800]:     ret = functor(name, args)
[   68.233298] cloud-init[1800]:           ^^^^^^^^^^^^^^^^^^^
[  OK  ] Reached target network-pre.target - Preparation for Network.
[   68.233443] cloud-init[1800]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 435, in main_init
[   68.350295] cloud-init[1800]:     init.apply_network_config(bring_up=bring_up_interfaces)
         Starting systemd-networkd.service - Network Configuration...
[   68.350444] cloud-init[1800]:   File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 998, in apply_network_config
[   68.478312] cloud-init[1800]:     netcfg, src = self._find_networking_config()
[   68.513303] cloud-init[1800]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[   68.547331] cloud-init[1800]:   File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 934, in _find_networking_config
[   68.602096] cloud-init[1800]:     if self.datasource and hasattr(self.datasource, "network_config"):
[   68.647123] cloud-init[1800]:                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[   68.690294] cloud-init[1800]:   File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceEc2.py", line 530, in network_config
[  OK  ] Started systemd-networkd.service - Network Configuration.
[   68.690452] cloud-init[1800]:     result = convert_ec2_metadata_network_config(
[  OK  ] Reached target network.target - Network.
[   68.820299] cloud-init[1800]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[   68.888308] cloud-init[1800]:   File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceEc2.py", line 1110, in convert_ec2_metadata_network_config
         Starting systemd-networkd-wait-onl…ait for Network to be Configured...
[   68.888459] cloud-init[1800]:     _configure_policy_routing(
[   69.020473] cloud-init[1800]:   File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceEc2.py", line 976, in _configure_policy_routing
[   69.083344] cloud-init[1800]:     subnet_prefix_routes = nic_metadata["subnet-ipv4-cidr-block"]
[   69.125302] cloud-init[1800]:                            ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
[   69.167328] cloud-init[1800]: KeyError: 'subnet-ipv4-cidr-block'
[   69.195339] cloud-init[1800]: ------------------------------------------------------------
[FAILED] Failed to start systemd-networkd-w… Wait for Network to be Configured.
See 'systemctl status systemd-networkd-wait-online.service' for details.
         Starting cloud-init.service - Init…t job (metadata service crawler)...
[  189.351640] cloud-init[1886]: Cloud-init v. 24.1.3-0ubuntu3 running 'init' at Sun, 12 May 2024 13:06:24 +0000. Up 189.34 seconds.
[  189.402414] cloud-init[1886]: ci-info: +++++++++++++++++++++++++++Net device info++++++++++++++++++++++++++++
[  189.451091] cloud-init[1886]: ci-info: +--------+-------+-----------+-----------+-------+-------------------+
[  189.498311] cloud-init[1886]: ci-info: | Device |   Up  |  Address  |    Mask   | Scope |     Hw-Address    |
[FAILED] Failed to start cloud-init.service…nit job (metadata service crawler).
See 'systemctl status cloud-init.service' for details.
[  189.498494] cloud-init[1886]: ci-info: +--------+-------+-----------+-----------+-------+-------------------+
[  189.663306] cloud-init[1886]: ci-info: | ens100 | False |     .     |     .     |   .   | 0e:2e:d5:59:49:01 |
[  189.663463] cloud-init[1886]: ci-info: | ens101 | False |     .     |     .     |   .   | 0e:76:d4:b0:0f:2b |
[  OK  ] Reached target cloud-config.target - Cloud-config availability.
[  189.711251] cloud-init[1886]: ci-info: | ens102 | False |     .     |     .     |   .   | 0e:f2:51:2a:17:5b |
[  OK  ] Reached target network-online.target - Network is Online.
[  189.799519] cloud-init[1886]: ci-info: | ens128 | False |     .     |     .     |   .   | 0e:36:0b:e1:71:13 |
[  OK  ] Reached target sysinit.target - System Initialization.
[  189.884520] cloud-init[1886]: ci-info: | ens129 | False |     .     |     .     |   .   | 0e:fb:57:73:e0:4d |
[  OK  ] Started acpid.path - ACPI Events Check.
[  190.019305] cloud-init[1886]: ci-info: | ens130 | False |     .     |     .     |   .   | 0e:4a:1e:b6:8f:dd |
[  OK  ] Started systemd-tmpfiles-clean.tim…y Cleanup of Temporary Directories.
[  190.097299] cloud-init[1886]: ci-info: | ens131 | False |     .     |     .     |   .   | 0e:57:1a:7c:dd:39 |
[  190.191123] cloud-init[1886]: ci-info: | ens32  | False |     .     |     .     |   .   | 0e:53:3c:8c:23:0f |
[  OK  ] Started update-notifier-download.t…hat failed at package install time.
[  190.238318] cloud-init[1886]: ci-info: | ens33  | False |     .     |     .     |   .   | 0e:a4:06:1f:b0:2b |
[  OK  ] Reached target paths.target - Path Units.
[  190.329302] cloud-init[1886]: ci-info: | ens34  | False |     .     |     .     |   .   | 0e:d8:91:48:6c:83 |
[  OK  ] Listening on acpid.socket - ACPID Listen Socket.
[  OK  ] Listening on cloud-init-hotplugd.s���t - cloud-init hotplug hook socket.
[  190.408424] cloud-init[1886]: ci-info: | ens35  | False |     .     |     .     |   .   | 0e:96:4d:ef:67:bb |
[  190.536125] cloud-init[1886]: ci-info: | ens64  | False |     .     |     .     |   .   | 0e:be:60:10:22:9d |
[  190.585122] cloud-init[1886]: ci-info: | ens65  | False |     .     |     .     |   .   | 0e:52:57:4b:63:13 |
[  190.633121] cloud-init[1886]: ci-info: | ens66  | False |     .     |     .     |   .   | 0e:53:9e:db:47:51 |
[  OK  ] Listening on dbus.socket - D-Bus System Message Bus Socket.
[  190.681314] cloud-init[1886]: ci-info: | ens67  | False |     .     |     .     |   .   | 0e:26:fc:f5:7d:45 |
[  OK  ] Listening on iscsid.socket - Open-iSCSI iscsid Socket.
[  190.765766] cloud-init[1886]: ci-info: | ens97  | False |     .     |     .     |   .   | 0e:44:9a:0f:a0:f9 |
[  190.852298] cloud-init[1886]: ci-info: |   lo   |  True | 127.0.0.1 | 255.0.0.0 |  host |         .         |
         Starting lxd-installer.socket - He…er to install lxd snap on demand...
[  190.852457] cloud-init[1886]: ci-info: |   lo   |  True |  ::1/128  |     .     |  host |         .         |
         Starting snapd.socket - Socket activation for snappy daemon...
[  190.988318] cloud-init[1886]: ci-info: +--------+-------+-----------+-----------+-------+-------------------+
[  191.072115] cloud-init[1886]: ci-info: +++++++++++++++++++Route IPv6 info+++++++++++++++++++
[  191.110848] cloud-init[1886]: ci-info: +-------+-------------+---------+-----------+-------+
[  OK  ] Listening on ssh.socket - OpenBSD Secure Shell server socket.
[  191.111088] cloud-init[1886]: ci-info: | Route | Destination | Gateway | Interface | Flags |
[  191.232121] cloud-init[1886]: ci-info: +-------+-------------+---------+-----------+-------+
[  191.272888] cloud-init[1886]: ci-info: +-------+-------------+---------+-----------+-------+
[  OK  ] Listening on uuidd.socket - UUID daemon activation socket.
[  191.273033] cloud-init[1886]: 2024-05-12 13:06:24,540 - util.py[WARNING]: failed stage init
[  191.395131] cloud-init[1886]: failed run of stage init
[  OK  ] Reached target remote-fs-pre.targe…reparation for Remote File Systems.
[  191.418443] cloud-init[1886]: ------------------------------------------------------------
[  OK  ] Reached target remote-fs.target - Remote File Systems.
[  OK  ] Finished blk-availability.service - Availability of block devices.
[  191.463505] cloud-init[1886]: Traceback (most recent call last):
[  191.612276] cloud-init[1886]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 774, in status_wrapper
[  OK  ] Listening on lxd-installer.socket …lper to install lxd snap on demand.
[  OK  ] Listening on snapd.socket - Socket activation for snappy daemon.
[  191.612420] cloud-init[1886]:     ret = functor(name, args)
[  191.777280] cloud-init[1886]:           ^^^^^^^^^^^^^^^^^^^
[  OK  ] Reached target sockets.target - Socket Units.
[  191.777476] cloud-init[1886]:   File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 435, in main_init
[  OK  ] Reached target basic.target - Basic System.
[  191.837317] cloud-init[1886]:     init.apply_network_config(bring_up=bring_up_interfaces)
[  191.962279] cloud-init[1886]:   File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 998, in apply_network_config
         Starting systemd-logind.service - User Login Management...
[  191.962461] cloud-init[1886]:     netcfg, src = self._find_networking_config()
[  192.084293] cloud-init[1886]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[  OK  ] Started acpid.service - ACPI event daemon.
[  192.084432] cloud-init[1886]:   File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 934, in _find_networking_config
[  192.205285] cloud-init[1886]:     if self.datasource and hasattr(self.datasource, "network_config"):
         Starting apport.service - automatic crash report generation...
[  192.205423] cloud-init[1886]:                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         Starting chrony.service - chrony, an NTP client/server...
[  192.328308] cloud-init[1886]:   File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceEc2.py", line 530, in network_config
[  192.421153] cloud-init[1886]:     result = convert_ec2_metadata_network_config(
[  192.421205] cloud-init[1886]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[  192.491117] cloud-init[1886]:   File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceEc2.py", line 1110, in convert_ec2_metadata_network_config
[  192.559089] cloud-init[1886]:     _configure_policy_routing(
[  192.583524] cloud-init[1886]:   File "/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceEc2.py", line 976, in _configure_policy_routing
[  192.647087] cloud-init[1886]:     subnet_prefix_routes = nic_metadata["subnet-ipv4-cidr-block"]
[  192.689117] cloud-init[1886]:                            ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
[  192.730279] cloud-init[1886]: KeyError: 'subnet-ipv4-cidr-block'
         Starting cloud-config.service - Ap…ttings specified in cloud-config...
[  192.730449] cloud-init[1886]: ------------------------------------------------------------
[  OK  ] Started cron.service - Regular background program processing daemon.
         Starting dbus.service - D-Bus System Message Bus...
[  OK  ] Started dmesg.service - Save initial kernel messages after boot.
         Starting e2scrub_reap.service - Re…ne ext4 Metadata Check Snapshots...
         Starting ec2-instance-connect-harv…ance Connect Host Key Harvesting...
[  193.058976] cloud-init[1927]: Cloud-init v. 24.1.3-0ubuntu3 running 'modules:config' at Sun, 12 May 2024 13:06:28 +0000. Up 193.03 seconds.
         Starting grub-common.service - Record successful boot for GRUB...
[  OK  ] Started irqbalance.service - irqbalance daemon.
         Starting networkd-dispatcher.servi…cher daemon for systemd-networkd...
         Starting polkit.service - Authorization Manager...
         Starting pollinate.service - Polli…e pseudo random number generator...
         Starting rsyslog.service - System Logging Service...
[  OK  ] Reached target getty-pre.target - Preparation for Logins.
         Starting snapd.seeded.service - Wait until snapd is fully seeded...
         Starting snapd.service - Snap Daemon...
         Starting sysstat.service - Resets System Activity Logs...
         Starting udisks2.service - Disk Manager...
[  OK  ] Started systemd-logind.service - User Login Management.
[  OK  ] Started dbus.service - D-Bus System Message Bus.
[  OK  ] Finished e2scrub_reap.service - Re…line ext4 Metadata Check Snapshots.
[  OK  ] Finished apport.service - automatic crash report generation.
[  OK  ] Finished sysstat.service - Resets System Activity Logs.
[  OK  ] Started unattended-upgrades.service - Unattended Upgrades Shutdown.
[  OK  ] Started networkd-dispatcher.servic…atcher daemon for systemd-networkd.
[  OK  ] Started rsyslog.service - System Logging Service.
[  OK  ] Finished grub-common.service - Record successful boot for GRUB.
         Starting grub-initrd-fallback.service - GRUB failed boot detection...
[  OK  ] Started polkit.service - Authorization Manager.
         Starting ModemManager.service - Modem Manager...
[  OK  ] Finished ec2-instance-connect-harv…stance Connect Host Key Harvesting.
[  OK  ] Finished grub-initrd-fallback.service - GRUB failed boot detection.
[  OK  ] Started chrony.service - chrony, an NTP client/server.
[  OK  ] Reached target time-sync.target - System Time Synchronized.
[  OK  ] Started apt-daily.timer - Daily apt download activities.
[  OK  ] Started apt-daily-upgrade.timer - …y apt upgrade and clean activities.
[  OK  ] Started dpkg-db-backup.timer - Daily dpkg database backup timer.
[  OK  ] Started e2scrub_all.timer - Period…Metadata Check for All Filesystems.
[  OK  ] Started fstrim.timer - Discard unused filesystem blocks once a week.
[  OK  ] Started fwupd-refresh.timer - Refresh fwupd metadata regularly.
[  OK  ] Started logrotate.timer - Daily rotation of log files.
[  OK  ] Started man-db.timer - Daily man-db regeneration.
[  OK  ] Started motd-news.timer - Message of the Day.
[  OK  ] Started sysstat-collect.timer - Ru…y accounting tool every 10 minutes.
[  OK  ] Started sysstat-summary.timer - Ge… of yesterday's process accounting.
[  OK  ] Started update-notifier-motd.timer… a new version of Ubuntu available.
[  OK  ] Reached target timers.target - Timer Units.
[  OK  ] Finished pollinate.service - Polli…the pseudo random number generator.
[  OK  ] Started udisks2.service - Disk Manager.
[  OK  ] Started ModemManager.service - Modem Manager.
[  OK  ] Finished cloud-config.service - Ap��settings specified in cloud-config.
         Starting hibinit-agent.service - E…instance hibernation setup agent...
         Starting systemd-user-sessions.service - Permit User Sessions...
[  OK  ] Finished systemd-user-sessions.service - Permit User Sessions.
         Starting plymouth-quit-wait.servic…d until boot process finishes up...
         Starting plymouth-quit.service - Terminate Plymouth Boot Screen...
[  OK  ] Finished plymouth-quit-wait.servic…old until boot process finishes up.
[  OK  ] Finished plymouth-quit.service - Terminate Plymouth Boot Screen.
[  OK  ] Started serial-getty@ttyS0.service - Serial Getty on ttyS0.
         Starting setvtrgb.service - Set console scheme...
[  OK  ] Finished setvtrgb.service - Set console scheme.
[  OK  ] Created slice system-getty.slice - Slice /system/getty.
[  OK  ] Started getty@tty1.service - Getty on tty1.
[  OK  ] Reached target getty.target - Login Prompts.
[  OK  ] Started snapd.service - Snap Daemon.
[  OK  ] Started snap.amazon-ssm-agent.amaz… amazon-ssm-agent.amazon-ssm-agent.
         Starting systemd-timedated.service - Time & Date Service...
[  OK  ] Started systemd-timedated.service - Time & Date Service.

Ubuntu 24.04 LTS i-0a808f75cccd2644a ttyS0

i-0a808f75cccd2644a login: [  OK  ] Started snap.amazon-ssm-agent.amaz… amazon-ssm-agent.amazon-ssm-agent.
[FAILED] Failed to start hibinit-agent.serv…2 instance hibernation setup agent.
See 'systemctl status hibinit-agent.service' for details.
[  OK  ] Started snap.amazon-ssm-agent.amaz… amazon-ssm-agent.amazon-ssm-agent.
[  OK  ] Started snap.amazon-ssm-agent.amaz… amazon-ssm-agent.amazon-ssm-agent.
[  OK  ] Started snap.amazon-ssm-agent.amaz�� amazon-ssm-agent.amazon-ssm-agent.
[  OK  ] Started snap.amazon-ssm-agent.amaz… amazon-ssm-agent.amazon-ssm-agent.
[  OK  ] Started snap.amazon-ssm-agent.amaz��� amazon-ssm-agent.amazon-ssm-agent.
[  OK  ] Started snap.amazon-ssm-agent.amaz… amazon-ssm-agent.amazon-ssm-agent.
[  OK  ] Started snap.amazon-ssm-agent.amaz… amazon-ssm-agent.amazon-ssm-agent.
[  OK  ] Started snap.amazon-ssm-agent.amaz… amazon-ssm-agent.amazon-ssm-agent.
[FAILED] Failed to start snap.amazon-ssm-ag… amazon-ssm-agent.amazon-ssm-agent.
See 'systemctl status snap.amazon-ssm-a���.amazon-ssm-agent.service' for details.
         Starting systemd-timedated.service - Time & Date Service...
[  OK  ] Started systemd-timedated.service - Time & Date Service.
[  OK  ] Finished snapd.seeded.service - Wait until snapd is fully seeded.
[  OK  ] Reached target multi-user.target - Multi-User System.
[  OK  ] Reached target graphical.target - Graphical Interface.
         Starting cloud-final.service - Execute cloud user/final scripts...
         Starting systemd-update-utmp-runle…- Record Runlevel Change in UTMP...
[  OK  ] Finished systemd-update-utmp-runle…e - Record Runlevel Change in UTMP.
[  231.642778] cloud-init[2599]: Cloud-init v. 24.1.3-0ubuntu3 running 'modules:final' at Sun, 12 May 2024 13:07:06 +0000. Up 231.62 seconds.
[  231.709053] cloud-init[2599]: 2024-05-12 13:07:06,817 - util.py[WARNING]: Running module ssh_authkey_fingerprints (<module 'cloudinit.config.cc_ssh_authkey_fingerprints' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh_authkey_fingerprints.py'>) failed

[  231.816394] cloud-init[2599]: Cloud-init v. 24.1.3-0ubuntu3 finished at Sun, 12 May 2024 13:07:06 +0000. Datasource DataSourceEc2Local.  Up 231.81 seconds
[FAILED] Failed to start cloud-final.servic…- Execute cloud user/final scripts.
See 'systemctl status cloud-final.service' for details.
[  OK  ] Reached target cloud-init.target - Cloud-init target.
```

**Comment by TheRealFalcon** [comment]
Thanks for the bug report @leezu . I put up a draft PR to address this at https://github.com/canonical/cloud-init/pull/5287

**Comment by leezu** [comment]
Thank you, @TheRealFalcon. Please let me know if you issues reproducing or validating the fix.

**Comment by TheRealFalcon** [comment]
@leezu , fix has been merged upstream. Downstream Ubuntu can be tracked in  https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/2066979

**Comment by leezu** [comment]
Thank you, @TheRealFalcon. When do you expect the fix to be packaged in jammy-updates or noble release?

**Comment by TheRealFalcon** [comment]
@leezu , I unfortunately do not have a timeline, but we are trying to get this released ASAP.
