### ISSUE TITLE
Traceback observed in logs while using user-data from file

### ISSUE THREAD

**Issue by sshedi** [canonical/cloud-init#5303]
# Bug report
While no data sources are used and user-data is provided by a file, a traceback is observed.

## Steps to reproduce the problem
Following is my user-data file:
```
#cloud-config

preserve_hostname: true

write_files:
-   content: Hello cloudinit
    path: /var/log/cloudinit-test.log
    permissions: '0644'
```

And then I'm doing:
```
cloud-init init --local
cloud-init -d modules --mode init --file user-data
cloud-init -d modules --mode config --file user-data
cloud-init -d modules --mode final --file user-data
```

And then in `/var/log/cloud-init.log`
```
...
2024-05-18 11:01:59,412 - util.py[DEBUG]: Failed to write boot finished file /var/lib/cloud/instance/boot-finished
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/cloudinit/config/cc_final_message.py", line 109, in handle
    util.write_file(boot_fin_fn, contents, ensure_dir_exists=False)
  File "/usr/lib/python3.11/site-packages/cloudinit/util.py", line 2308, in write_file
    with open(filename, omode) as fh:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/cloud/instance/boot-finished'
2024-05-18 11:01:59,413 - cc_final_message.py[WARNING]: Used fallback datasource
...
```
## Environment details
- Cloud-init version: 24.1.4
- Operating System Distribution: PhotonOS
- Cloud provider, platform or installer type: NA

**Comment by TheRealFalcon** [comment]
@sshedi , thanks for the bug report, but I am unable to reproduce this. Would it be possible to attach the tarball resulting from `cloud-init collect-logs`?

Based on the traceback, it looks like cloud-init is complaing that `/var/lib/cloud/instance` doesn't exist when attempting to write `/var/lib/cloud/instance/boot-finished`. However, `/var/lib/cloud/instance` should get created when `cloud-init init --local` is run. It does when I run this locally.

**Comment by sshedi** [comment]
Thanks for taking a look at this. Attaching the support tarball.
[Uploading cloud-init.tar.gz…]()

**Comment by TheRealFalcon** [comment]
Thanks. I can reproduce this when there is no datasource list defined or datasource detected.

**Comment by maburlik** [comment]
I'm hitting the same error using NoCloud data source, for a lengthy cloud-init user-config. I'm running a lot of deployments and once a day/per times per week this is hit. Does anyone have an understanding of the cause?

```
2024-09-24 21:20:22,510 - util.py[DEBUG]: Cloud-init v. 24.2-0ubuntu1~22.04.1 finished at Tue, 24 Sep 2024 21:20:22 +0000. Datasource DataSourceNoCloud [seed=/dev/vdb][dsmode=net].  Up 70.50 seconds
2024-09-24 21:20:22,511 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/boot-finished - wb: [644] 67 bytes
2024-09-24 21:20:22,513 - util.py[WARNING]: Failed to write boot finished file /var/lib/cloud/instance/boot-finished
2024-09-24 21:20:22,514 - util.py[DEBUG]: Failed to write boot finished file /var/lib/cloud/instance/boot-finished
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_final_message.py", line 76, in handle
    util.write_file(boot_fin_fn, contents, ensure_dir_exists=False)
  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 2291, in write_file
    with open(filename, omode) as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/cloud/instance/boot-finished'
```

**Comment by aciba90** [comment]
I have not yet been able to reproduce this. Could you, @TheRealFalcon @sshedi or @maburlik, please run `ls -hal /var/lib/cloud/` on the instance and paste the output?

**Comment by rjsilvams** [comment]
I work with @maburlik and I would like to clarify one detail.

Do you mean the output of ls -hal /var/lib/cloud/ or ls -hal /var/lib/cloud/instance?

**Comment by TheRealFalcon** [comment]
This is a symptom of having no datasource found during cloud-init's earlier stages.

Is cloud-init being run by systemd as part of boot? If so, do you see an "ERROR" or  "Traceback" earlier in the logs indicating that the datasource could not be initialized? If so, that is the root cause of this.

If cloud-init is being run separately on the CLI, ensure [all cloud-init boot stages](https://docs.cloud-init.io/en/latest/explanation/boot.html) are run.

If neither of those are relevant, please run `cloud-init collect-logs` and attach the resulting tarball.

**Comment by rjsilvams** [comment]
> This is a symptom of having no datasource found during cloud-init's earlier stages.
> 
> Is cloud-init being run by systemd as part of boot? 

Answer: Yes.

> If so, do you see an "ERROR" or "Traceback" earlier in the logs indicating that the datasource could not be initialized? If so, that is the root cause of this.

Answer: No. None of the log files contains any error or trace about data sources not being initialized.

> If cloud-init is being run separately on the CLI, ensure [all cloud-init boot stages](https://docs.cloud-init.io/en/latest/explanation/boot.html) are run.
> 
Answer: Not applicable

> If neither of those are relevant, please run `cloud-init collect-logs` and attach the resulting tarball.

Answer: Will do and get back to you. Thanks.
