### ISSUE TITLE
cloud-init fails to render eni config on multi-iface systems

### ISSUE THREAD

**Issue by rye-stripe** [canonical/cloud-init#5318]
# Bug report
After the cloud-init upgrade from to `23.4.4-0ubuntu0~20.04.1` to `24.1.3-0ubuntu1~20.04.1` on focal, we can no longer boot EC2 hosts with multiple network interfaces (ena devices). The init-local stage fails to write out valid configuration to /etc/network/interfaces.d/50-cloud-init.cfg. Without the config, `ifupdown` does not bring up any of the two interfaces, leading to a host that can't communicate over network.

```
2024-05-14 14:27:59,891 - util.py[WARNING]: failed stage init-local
failed run of stage init-local
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 781, in status_wrapper
    ret = functor(name, args)
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 442, in main_init
    init.apply_network_config(bring_up=bring_up_interfaces)
  File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 1060, in apply_network_config
    return self.distro.apply_network_config(
  File "/usr/lib/python3/dist-packages/cloudinit/distros/__init__.py", line 440, in apply_network_config
    self._write_network_state(network_state, renderer)
  File "/usr/lib/python3/dist-packages/cloudinit/distros/debian.py", line 129, in _write_network_state
    return super()._write_network_state(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/cloudinit/distros/__init__.py", line 364, in _write_network_state
    renderer.render_network_state(network_state)
  File "/usr/lib/python3/dist-packages/cloudinit/net/eni.py", line 561, in render_network_state
    util.write_file(fpeni, header + self._render_interfaces(network_state))
  File "/usr/lib/python3/dist-packages/cloudinit/net/eni.py", line 544, in _render_interfaces
    self._render_iface(iface, render_hwaddress=render_hwaddress)
  File "/usr/lib/python3/dist-packages/cloudinit/net/eni.py", line 485, in _render_iface
    lines.extend(self._render_route(route, indent="    "))
  File "/usr/lib/python3/dist-packages/cloudinit/net/eni.py", line 406, in _render_route
    route_line += "%s %s %s" % (default_gw, mapping[k], route[k])
KeyError: 'gateway'
```

After some debugging, I've traced the issue to https://github.com/canonical/cloud-init/commit/0ca5f31043e2d98eab31a43d9dde9bdaef1435cb . Specifically, this commit [adds gateway-less](https://github.com/canonical/cloud-init/blob/0ca5f31043e2d98eab31a43d9dde9bdaef1435cb/cloudinit/sources/DataSourceEc2.py#L1017-L1020) routing table entries, which causes the [eni renderer to blow up](https://github.com/canonical/cloud-init/blob/739c5f63c41fe08f72c9138f300fe117f63d3403/cloudinit/net/eni.py#L405-L406) with the exception above. v24.1.3 happens to work on single interface systems, because ec2 datasource [removes](https://github.com/canonical/cloud-init/blob/0ca5f31043e2d98eab31a43d9dde9bdaef1435cb/cloudinit/sources/DataSourceEc2.py#L1048C1-L1049C1) routes if there's only a single network device.

## Steps to reproduce the problem
Boot an ec2 instance with 2 (or more) ena devices and the following cloud-init config:
```
system_info:
  network:
    renderers: ['eni', 'netplan', 'sysconfig']
```

## Environment details
- Cloud-init version: 24.1.3-0ubuntu1~20.04.1
- Operating System Distribution: Ubuntu Focal
- Cloud provider, platform or installer type: EC2, any instance type + 2 elastic network interfaces (ENAs) configured

## cloud-init logs
See exception above.

**Comment by TheRealFalcon** [comment]
@rye-stripe , thanks for raising this issue. I put up #5321 to address this.

As a workaround (and best practice for your use case), in your `cloud.cfg`, you can include the following line under your `renderers` line:
```
activators: ['eni', 'netplan', 'network-manager', 'networkd']
```
