### ISSUE TITLE
On Photon, system incorrectly issuing "sudo sshd restart" in runcmd

### ISSUE THREAD

**Issue by dark2phoenix** [canonical/cloud-init#5358]
# Bug report
The file /var/lib/cloud/instance/scripts/runcmd has the following contents
```
#!/bin/sh
sudo service sshd restart
````

This causes the following error in cloud-init.log:
```
024-06-03 17:14:52,477 - subp.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/runcmd'] with allowed return codes [0] (shell=False, capture=False)
2024-06-03 17:14:52,511 - subp.py[DEBUG]: Unexpected error while running command.
Command: ['/var/lib/cloud/instance/scripts/runcmd']
Exit code: 1
Reason: -
Stdout: -
Stderr: -
2024-06-03 17:14:52,511 - cc_scripts_user.py[WARNING]: Failed to run module scripts_user (scripts in /var/lib/cloud/instance/scripts)
2024-06-03 17:14:52,511 - handlers.py[DEBUG]: finish: modules-final/config-scripts_user: FAIL: running config-scripts_user with frequency once-per-instance
2024-06-03 17:14:52,512 - util.py[WARNING]: Running module scripts_user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3.11/site-packages/cloudinit/config/cc_scripts_user.py'>) failed
2024-06-03 17:14:52,512 - util.py[DEBUG]: Running module scripts_user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3.11/site-packages/cloudinit/config/cc_scripts_user.py'>) failed
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/cloudinit/config/modules.py", line 286, in _run_modules
    ran, _r = cc.run(
              ^^^^^^^
  File "/usr/lib/python3.11/site-packages/cloudinit/cloud.py", line 71, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail) 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cloudinit/helpers.py", line 156, in run
    results = functor(**args)
              ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/cloudinit/config/cc_scripts_user.py", line 53, in handle
    subp.runparts(runparts_path)
  File "/usr/lib/python3.11/site-packages/cloudinit/subp.py", line 393, in runparts
    raise RuntimeError( 
RuntimeError: Runparts: 1 failures (runcmd) in 1 attempted commands
```
The following underlying error message is added to the cloud-init-output.log:
```
Cloud-init v. 24.1.4 running 'modules:final' at Mon, 03 Jun 2024 17:14:52 +0000. Up 52.15 seconds.
sudo: service: command not found
2024-06-03 17:14:52,511 - cc_scripts_user.py[WARNING]: Failed to run module scripts_user (scripts in /var/lib/cloud/instance/scripts)
2024-06-03 17:14:52,512 - util.py[WARNING]: Running module scripts_user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3.11/site-packages/cloudinit/config/cc_scripts_user.py'>) failed
```

Ultimately this leads to cloud-init thinking it has failed so the status will forever be "error"
```
2024-06-03 17:14:52,677 - util.py[DEBUG]: cloud-init mode 'modules' took 0.393 seconds (0.39)
2024-06-03 17:14:52,677 - handlers.py[DEBUG]: finish: modules-final: FAIL: running modules for final
```
```
cloud-init status
status: error
```
All other indications are, though, that the system is functioning normally.  New SSH keys are generated and configuration is applied.  I didn't notice this till I started checking on the status of cloud-init as part of the overall build process.

Photon is a Systemd based OS so it should be `systemctl restart sshd`. I cannot figure out how this file is getting created/populated so I can submit a patch.  If someone can help me figure out where this is happening, I will make the patch for it.

## Steps to reproduce the problem
1. Define a simple cloud-init script
````
 #cloud-config
 # vim: syntax=yaml
  users:
    - name: saltuser
      sudo: ALL=(ALL) NOPASSWD:ALL
      groups: sudo, users
      lock_passwd: false
````
2. Deploy system with cloud-init

## Environment details
- Cloud-init version:  24.1.4
- Operating System Distribution:  Tested on Photon 4.0rev2 and 5.0
- Cloud provider, platform or installer type:
vSphere VM

## cloud-init logs
See in-line above

**Comment by dark2phoenix** [comment]
I think I have determined that this is coming from Aria Automation adding it in the background and not directly from anything cloud-init is doing.  I'm going to close this for now and pursue with Aria Automation.
