### ISSUE TITLE
Fix the complexity of random passwords generated by the rand_user_password() method

### ISSUE THREAD

**Issue by xiaoge1001** [canonical/cloud-init#5814]
# Bug report

The complexity of the random password generated by the rand_user_password() method may not meet the security configuration requirements of the system authentication module. chpasswd will fail.

## Steps to reproduce the problem

```
#cloud-config
chpasswd:
  expire: False
  list: |
    user1:openEuler@12#$
    user2:RANDOM
```

## Environment details
- Cloud-init version: cloud-init-23.4.1-3.oe2403
- Operating System Distribution:openEuler-24.03-LTS
- Cloud provider, platform or installer type:nocloud

## cloud-init logs

```
2024-10-11 16:18:40,854 - cc_set_passwords.py[DEBUG]: Handling input for chpasswd as multiline string.
2024-10-11 16:18:40,854 - cc_set_passwords.py[DEBUG]: Changing password for ['user1', 'user2']:
2024-10-11 16:18:40,854 - subp.py[DEBUG]: Running command ['chpasswd'] with allowed return codes [0] (shell=False, capture=True)
2024-10-11 16:18:40,925 - util.py[WARNING]: Failed to set passwords with chpasswd for ['user1', 'user2']
2024-10-11 16:18:40,925 - util.py[DEBUG]: Failed to set passwords with chpasswd for ['user1', 'user2']
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/cloudinit/config/cc_set_passwords.py", line 259, in handle
    distro.chpasswd(plist_in, hashed=False)
  File "/usr/lib/python3.11/site-packages/cloudinit/distros/__init__.py", line 925, in chpasswd
    subp.subp(cmd, data=payload)
  File "/usr/lib/python3.11/site-packages/cloudinit/subp.py", line 316, in subp
    raise ProcessExecutionError(
cloudinit.subp.ProcessExecutionError: Unexpected error while running command.
Command: ['chpasswd']
Exit code: 1
Reason: -
Stdout:
Stderr: BAD PASSWORD: The password contains less than 3 character classes
        BAD PASSWORD: The password contains less than 3 character classes
        BAD PASSWORD: The password contains less than 3 character classes
        chpasswd: (user user2) pam_chauthtok() failed, error:
        Have exhausted maximum number of retries for service
        chpasswd: (line 2, user user2) password not changed
2024-10-11 16:18:40,931 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config.d/50-cloud-init.conf (quiet=False)
2024-10-11 16:18:40,932 - util.py[DEBUG]: Read 27 bytes from /etc/ssh/sshd_config.d/50-cloud-init.conf
2024-10-11 16:18:40,932 - ssh_util.py[DEBUG]: line 1: option PasswordAuthentication already set to yes
```

**Comment by TheRealFalcon** [comment]
Cloud-init's random password generation does not take character classes into account. This would be a helpful addition.
