### ISSUE TITLE
`failed stage modules-final` when using `package_reboot_if_required: true` in cloud-init.yaml on Ubuntu Noble LXD VMs

### ISSUE THREAD

**Issue by rajannpatel** [canonical/cloud-init#5849]
# Bug report
Using `package_upgrade: true` in cloud-init.yaml on Ubuntu Noble LXD VMs causes Python errors in cloud-init-output.log.

## Steps to reproduce the problem
cloud-init.yaml file:
```yaml
#cloud-config

# `apt upgrade`
package_upgrade: true

# restart if necessary
package_reboot_if_required: true
```
```bash
lxc launch ubuntu:24.04 test --config=user.user-data="$(cat cloud-init.yaml)" --vm
lxc exec test -- tail -f /var/log/cloud-init-output.log
```

This issue is specific to `--vm`, and does not appear when using system containers in LXD.

## Environment details
- Cloud-init version: Cloud-init v. 24.3.1-0ubuntu0~24.04.2
- Operating System Distribution: Noble
- Cloud provider, platform or installer type: LXD VM on Ubuntu Noble

## cloud-init logs
cloud-init-output.log:

```
2024-10-31 11:03:18,695 - cc_package_update_upgrade_install.py[WARNING]: Rebooting after upgrade or install per /var/run/reboot-required
Cloud-init 24.3.1-0ubuntu0~24.04.2 received SIGTERM, exiting...
  Filename: /usr/lib/python3/dist-packages/cloudinit/config/cc_package_update_upgrade_install.py
  Function: _fire_reboot
  Line number: 55
    Filename: /usr/lib/python3/dist-packages/cloudinit/config/cc_package_update_upgrade_install.py
    Function: handle
    Line number: 114
      Filename: /usr/lib/python3/dist-packages/cloudinit/helpers.py
      Function: run
      Line number: 156
2024-10-31 11:03:18,822 - util.py[ERROR]: Cloud-init 24.3.1-0ubuntu0~24.04.2 received SIGTERM, exiting...
  Filename: /usr/lib/python3/dist-packages/cloudinit/config/cc_package_update_upgrade_install.py
  Function: _fire_reboot
  Line number: 55
    Filename: /usr/lib/python3/dist-packages/cloudinit/config/cc_package_update_upgrade_install.py
    Function: handle
    Line number: 114
      Filename: /usr/lib/python3/dist-packages/cloudinit/helpers.py
      Function: run
      Line number: 156
2024-10-31 11:03:18,824 - main.py[ERROR]: failed stage modules-final
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 831, in status_wrapper
    ret = functor(name, args)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 673, in main_modules
    return run_module_section(mods, name, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 160, in run_module_section
    (which_ran, failures) = mods.run_section(full_section_name)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cloudinit/config/modules.py", line 367, in run_section
    return self._run_modules(active_mods)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cloudinit/config/modules.py", line 286, in _run_modules
    ran, _r = cc.run(
              ^^^^^^^
  File "/usr/lib/python3/dist-packages/cloudinit/cloud.py", line 71, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cloudinit/helpers.py", line 156, in run
    results = functor(**args)
              ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_package_update_upgrade_install.py", line 114, in handle
    _fire_reboot()
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_package_update_upgrade_install.py", line 55, in _fire_reboot
    time.sleep(wait_time)
  File "/usr/lib/python3/dist-packages/cloudinit/signal_handler.py", line 48, in _handle_exit
    sys.exit(rc)
SystemExit: 1
failed run of stage modules-final
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 831, in status_wrapper
    ret = functor(name, args)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 673, in main_modules
    return run_module_section(mods, name, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 160, in run_module_section
    (which_ran, failures) = mods.run_section(full_section_name)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cloudinit/config/modules.py", line 367, in run_section
    return self._run_modules(active_mods)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cloudinit/config/modules.py", line 286, in _run_modules
    ran, _r = cc.run(
              ^^^^^^^
  File "/usr/lib/python3/dist-packages/cloudinit/cloud.py", line 71, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cloudinit/helpers.py", line 156, in run
    results = functor(**args)
              ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_package_update_upgrade_install.py", line 114, in handle
    _fire_reboot()
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_package_update_upgrade_install.py", line 55, in _fire_reboot
    time.sleep(wait_time)
  File "/usr/lib/python3/dist-packages/cloudinit/signal_handler.py", line 48, in _handle_exit
    sys.exit(rc)
SystemExit: 1
------------------------------------------------------------
```

**Comment by TheRealFalcon** [comment]
Thanks for the bug report. I can reproduce the behavior. The `package_reboot_if_required: true` causes cloud-init to issue a reboot which then kills the cloud-init process, leading to cloud-init logging the error.

**Comment by JamesColeman-LW** [comment]
Hello,

I think the following bug I reported at MaaS is related, sharing in-case it is.

https://bugs.launchpad.net/maas/+bug/2089185

**Comment by holmanb** [comment]
Hi @rajannpatel. I just linked a PR that I think should probably solve the issue. Could you please test if this solves the issue for you?

**Comment by rajannpatel** [comment]
@holmanb - thank you for fixing this issue. I tested with the basic cloud-init.yaml file in this bug report and a long running cloud-init.yaml file on Noble LXD virtual machines image with fingerprint `63e801c054391f66daa35b8d0205d92b7e405092546f9df2e4be2adb2e08a71d`. The tests by my reading were successful. I saw the appropriate notification that a reboot was required, cloud-init waited for the appropriate time to reboot the machine, and then proceeded to complete the remainder of the tasks once the reboot was complete.

I observed the /var/log/cloud-init-output.log in each VM to validate, and used the following script to perform my test:

```bash
#!/bin/bash

TODAY=$(date +%a%H%M | tr '[:upper:]' '[:lower:]')
ARCH="amd64"
LXD_VIRTUALMACHINES=("noble")
CLOUD_INIT=$(cat <<EOF
#cloud-config
package_upgrade: true
package_reboot_if_required: true
EOF
)

get_fingerprint() {
  local RELEASE=$1
  local TYPE=$2
  lxc image list ubuntu: arch=$ARCH release="$RELEASE" type="$TYPE" --format yaml | \
    yq e ".[] | .fingerprint" - | tail -1
}

for RELEASE in "${LXD_VIRTUALMACHINES[@]}"; do
  INSTANCE_NAME="$TODAY-vm-$RELEASE-$(shuf -i 100-999 -n 1)"
  if [[ -n "${LXD_VIRTUALMACHINE_FINGERPRINTS[$RELEASE]}" ]]; then
    FINGERPRINT=${LXD_VIRTUALMACHINE_FINGERPRINTS[$RELEASE]}
  else
    FINGERPRINT=$(get_fingerprint "$RELEASE" "virtual-machine")
    echo "Retrieved fingerprint for $RELEASE VM: $FINGERPRINT"
  fi
  if [ -n "$FINGERPRINT" ]; then
    echo "$RELEASE VM image fingerprint: $FINGERPRINT"
    lxc launch ubuntu:"$FINGERPRINT" "TEST-1-$INSTANCE_NAME" --vm --config=user.user-data="$CLOUD_INIT"
    wget -P /tmp https://raw.githubusercontent.com/rajannpatel/ubuntupbx/refs/heads/main/noble/cloud-init.yaml
    lxc launch ubuntu:"$FINGERPRINT" "TEST-2-$INSTANCE_NAME" --vm --config=user.user-data="$(cat /tmp/cloud-init.yaml)"
  else
    echo "No fingerprint found for release $RELEASE VM."
  fi
done
```

Thanks for fixing this!

**Comment by rajannpatel** [comment]
This exact same bug has resurfaced in Cloud-init v. 24.3.1-0ubuntu0~24.04.2 :-(

Use this cloud-init.yaml file:
```yaml
#cloud-config

# `apt upgrade`
package_upgrade: true

# restart if necessary
package_reboot_if_required: true
```

Launch as follows:
```shell
lxc launch ubuntu:24.04 testvm --config=user.user-data="$(cat cloud-init.yaml)" --vm
```

Failure output:
```text
Restarting services...
 systemctl restart polkit.service

Service restarts being deferred:
 systemctl restart cloud-final.service
 /etc/needrestart/restart.d/dbus.service
 systemctl restart unattended-upgrades.service

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
2025-01-07 01:36:11,817 - cc_package_update_upgrade_install.py[WARNING]: Rebooting after upgrade or install per /var/run/reboot-required
Cloud-init 24.3.1-0ubuntu0~24.04.2 received SIGTERM, exiting...
  Filename: /usr/lib/python3/dist-packages/cloudinit/config/cc_package_update_upgrade_install.py
  Function: _fire_reboot
  Line number: 55
    Filename: /usr/lib/python3/dist-packages/cloudinit/config/cc_package_update_upgrade_install.py
    Function: handle
    Line number: 114
      Filename: /usr/lib/python3/dist-packages/cloudinit/helpers.py
      Function: run
      Line number: 156
2025-01-07 01:36:11,924 - util.py[ERROR]: Cloud-init 24.3.1-0ubuntu0~24.04.2 received SIGTERM, exiting...
  Filename: /usr/lib/python3/dist-packages/cloudinit/config/cc_package_update_upgrade_install.py
  Function: _fire_reboot
  Line number: 55
    Filename: /usr/lib/python3/dist-packages/cloudinit/config/cc_package_update_upgrade_install.py
    Function: handle
    Line number: 114
      Filename: /usr/lib/python3/dist-packages/cloudinit/helpers.py
      Function: run
      Line number: 156
2025-01-07 01:36:11,925 - main.py[ERROR]: failed stage modules-final
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 831, in status_wrapper
    # Guess it worked
          ^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 673, in main_modules
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 160, in run_module_section
  File "/usr/lib/python3/dist-packages/cloudinit/config/modules.py", line 367, in run_section
    )
      
  File "/usr/lib/python3/dist-packages/cloudinit/config/modules.py", line 286, in _run_modules
    func_params = func_signature.parameters
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cloudinit/cloud.py", line 71, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cloudinit/helpers.py", line 156, in run
    results = functor(**args)
              ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_package_update_upgrade_install.py", line 114, in handle
    _fire_reboot()
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_package_update_upgrade_install.py", line 55, in _fire_reboot
    time.sleep(wait_time)
  File "/usr/lib/python3/dist-packages/cloudinit/signal_handler.py", line 48, in _handle_exit
    sys.exit(rc)
SystemExit: 1
failed run of stage modules-final
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 831, in status_wrapper
    # Guess it worked
          ^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 673, in main_modules
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 160, in run_module_section
  File "/usr/lib/python3/dist-packages/cloudinit/config/modules.py", line 367, in run_section
    )
      
  File "/usr/lib/python3/dist-packages/cloudinit/config/modules.py", line 286, in _run_modules
    func_params = func_signature.parameters
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cloudinit/cloud.py", line 71, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cloudinit/helpers.py", line 156, in run
    results = functor(**args)
              ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_package_update_upgrade_install.py", line 114, in handle
    _fire_reboot()
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_package_update_upgrade_install.py", line 55, in _fire_reboot
    time.sleep(wait_time)
  File "/usr/lib/python3/dist-packages/cloudinit/signal_handler.py", line 48, in _handle_exit
    sys.exit(rc)
SystemExit: 1
------------------------------------------------------------
```

**Comment by holmanb** [comment]
Hi @rajannpatel

We just merged the fix for this issue in upstream.

**Comment by Raboo** [comment]
@holmanb Will this be fix perhaps be backported so this can be fixed for Noble or do we have to wait for Ubuntu 26.04?
I noticed that this randomly kills an in progress apt-get dist-upgrade. So like every third node gets a broken apt.

**Comment by holmanb** [comment]
> [@holmanb](https://github.com/holmanb) Will this be fix perhaps be backported

Yes, 24.4.1 contains the fix and will be backported

**Comment by Raboo** [comment]
Is there a way to track it when it is backported to and released to Ubuntu Noble?

**Comment by jivanpal** [comment]
Likewise for 22.04/Jammy.

**Comment by TheRealFalcon** [comment]
@Raboo and @jivanpal , Ubuntu packages are tracked in Launchpad. In particular, you can see this bug at https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/2094208 . The fix will need to go through Ubuntu's [SRU](https://cloudinit.readthedocs.io/en/latest/reference/ubuntu_stable_release_updates.html) process, but the linked bug is where status will be tracked.

**Comment by ani-sinha** [comment]
@TheRealFalcon I have a question. We are seeing an issue where when `cc_ssh.py` generates the following warning, 
```
Jun 13 06:01:11 hao-rhel96-client-cloudinit21 cloud-init[962]: 2025-06-13 06:01:11,556 - lifecycle.py[DEPRECATED]: 'users' of type <class 'dict'> is deprecated in 22.2 and scheduled to be removed in 27.2. Use 'users' as a list.
```
cloud-init is getting killed by SIGTERM. Applying this patch fixes it. 
If the deprecation log is changed to `INFO` no `SIGTERM` is generated. 

See https://issues.redhat.com/browse/RHEL-96831

How is it possible for cloud-init to get `SIGTERM` when a `WARNING` level log is generated?

**Comment by TheRealFalcon** [comment]
@ani-sinha , I can't access that issue. Applying which patch fixes it? The one from the PR that fixed this issue?

I'm guessing that the warning is a red herring and that you're running into an unrelated bug or issue, but I don't have enough information at the moment.

**Comment by ani-sinha** [comment]
> [@ani-sinha](https://github.com/ani-sinha) , I can't access that issue. 

OK I raised this https://github.com/canonical/cloud-init/issues/6280

> Applying which patch fixes it? The one from the PR that fixed this issue?

https://github.com/canonical/cloud-init/pull/5913 . That is, https://github.com/TheRealFalcon/cloud-init/commit/4d559e7328452df355c0023fd9068592c57b7430 .

> I'm guessing that the warning is a red herring and that you're running into an unrelated bug or issue, but I don't have enough information at the moment.

What I have understood is that something is triggering a reboot and due to the patch above, `subp.runparts()` is ignoring `SIGTERM` so cloud-init exists gracefully. 
What I do not understand is the connection with the deprecated config warning which when changed to info somehow does not manifest this issue.
