### ISSUE TITLE
log_util.py[ERROR]: Cloud-init 24.4-0ubuntu1~20.04.1 received SIGTERM,

### ISSUE THREAD

**Issue by ritikgohate** [canonical/cloud-init#5944]
# Bug report
Since the release of new update i.e 24.4. We are receiving  " log_util.py[ERROR]: Cloud-init 24.4-0ubuntu1~20.04.1 received SIGTERM," which has affected our startup script's execution flow. Before this release, we were able to provisioning new VMs and even rebuild was flawless.

## Steps to reproduce the problem
Building a new Ubuntu VM or Rebuilding the existing one.

## Environment details
- Cloud-init version: 24.4-0ubuntu1~20.04.1
- Operating System Distribution: 20.04- 
- Cloud provider, platform or installer type: Google Cloud Platform

## cloud-init logs
2024-12-25 08:10:10,581 - performance.py[DEBUG]: Writing to console took 0.264 seconds
2024-12-25 08:10:10,581 - log_util.py[ERROR]: Cloud-init 24.4-0ubuntu1~20.04.1 received SIGTERM, exiting...
  Filename: /usr/lib/python3.8/subprocess.py
  Function: _try_wait
  Line number: 1764
    Filename: /usr/lib/python3.8/subprocess.py
    Function: _wait
    Line number: 1806
      Filename: /usr/lib/python3.8/subprocess.py
      Function: wait
      Line number: 1083
2024-12-25 08:10:10,581 - performance.py[DEBUG]: Running ['/var/lib/cloud/instance/scripts/part-001'] took 48.635 seconds
2024-12-25 08:10:10,582 - handlers.py[DEBUG]: finish: modules-final/config-scripts_user: FAIL: running config-scripts_user with frequency once-per-instance
2024-12-25 08:10:10,582 - main.py[ERROR]: failed stage modules-final
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 927, in status_wrapper
    ret = functor(name, args)
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 767, in main_modules
    return run_module_section(mods, name, name)
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 145, in run_module_section
    (which_ran, failures) = mods.run_section(full_section_name)
  File "/usr/lib/python3/dist-packages/cloudinit/config/modules.py", line 379, in run_section
    return self._run_modules(active_mods)
  File "/usr/lib/python3/dist-packages/cloudinit/config/modules.py", line 295, in _run_modules
    ran, _r = cc.run(
  File "/usr/lib/python3/dist-packages/cloudinit/cloud.py", line 60, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
  File "/usr/lib/python3/dist-packages/cloudinit/helpers.py", line 156, in run
    results = functor(**args)
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py", line 38, in handle
    subp.runparts(runparts_path)
  File "/usr/lib/python3/dist-packages/cloudinit/subp.py", line 371, in runparts
    subp(prefix + [exe_path], capture=False)
  File "/usr/lib/python3/dist-packages/cloudinit/subp.py", line 272, in subp
    out, err = sp.communicate(data, timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1020, in communicate
    self.wait()
  File "/usr/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1806, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.8/subprocess.py", line 1764, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/usr/lib/python3/dist-packages/cloudinit/signal_handler.py", line 48, in _handle_exit
    sys.exit(rc)
SystemExit: 1
2024-12-25 08:10:10,605 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)

**Comment by ritikgohate** [comment]
At least, let us know how can we avoid using 24.4 version while provisioning new VMs ? We want to provision new VMs with cloud-init 24.3.1only.

**Comment by TheRealFalcon** [comment]
In order to diagnose your issue, please run [cloud-init collect-logs](https://docs.cloud-init.io/en/latest/howto/bugs.html#collect-logs) and upload the results here.

> At least, let us know how can we avoid using 24.4 version while provisioning new VMs ? We want to provision new VMs with cloud-init 24.3.1only.

It's hard to know what you're asking for here without understand your provisioning process. If you're asking how to downgrade cloud-init in Ubuntu, you can see the available versions in apt with
```
apt list -a cloud-init
```
and then downgrade with
```
sudo apt install cloud-init=<version>
```

**Comment by ritikgohate** [comment]
@Thanzex Thanks for sharing your findings here. Hoping to get it resolved in the upcoming version.

**Comment by holmanb** [comment]
> Do you know if there's a way to downgrade cloud-init in-place before running the package installs?

You might want to use an ami that contains the previous version of cloud-init, until the fix is released.

**Comment by AdilKh4n** [comment]
Hi Folks, is this bug fixed in version 24.4.1? We are seeing this issue on version 24.4.0.

**Comment by TheRealFalcon** [comment]
@AdilKh4n , yes this should be [fixed](https://github.com/canonical/cloud-init/pull/5913) in [24.4.1](https://github.com/canonical/cloud-init/releases/tag/24.4.1)
